// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dev.octri.demo.pokeapiUnofficialSdk

class BerriesNamespace(private val clientConfig: ClientConfig) {
    /**
     * Lists berries, which Pokémon can eat to restore HP or status conditions, enhance stats, or
     * negate damage. Use `limit` and `offset` to select a result window, and `q` to filter by berry
     * name on a local API instance.
     *
     * Berries are small fruits that can provide HP and status condition restoration, stat
     * enhancement, and even damage negation when eaten by Pokémon. Check out Bulbapedia for greater
     * detail.
     */
    fun list(
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
    ): PaginatedBerrySummaryList {
        return dev.octri.demo.pokeapiUnofficialSdk.methods.Berries.berryList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )
    }

    /**
     * Lists berries, which Pokémon can eat to restore HP or status conditions, enhance stats, or
     * negate damage. Use `limit` and `offset` to select a result window, and `q` to filter by berry
     * name on a local API instance.
     *
     * Berries are small fruits that can provide HP and status condition restoration, stat
     * enhancement, and even damage negation when eaten by Pokémon. Check out Bulbapedia for greater
     * detail.
     */
    fun listPaginated(
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
        yieldFn: (BerrySummary) -> Boolean,
    ) {
        dev.octri.demo.pokeapiUnofficialSdk.methods.Berries.berryListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )
    }

    /**
     * Retrieves a berry and its growing properties, firmness, flavors, associated item, and natural
     * gift data. Supply the berry's `id` as a string or integer to look up the record.
     *
     * Berries are small fruits that can provide HP and status condition restoration, stat
     * enhancement, and even damage negation when eaten by Pokémon. Check out Bulbapedia for greater
     * detail.
     */
    fun retrieve(id: String, options: RequestOptions? = null): BerryDetail {
        return dev.octri.demo.pokeapiUnofficialSdk.methods.Berries.berryRetrieve(
            clientConfig,
            id,
            options,
        )
    }

    /**
     * Lists berry firmness categories, which describe how soft or hard berries are. Use `limit` and
     * `offset` to select a result window, and `q` to filter categories by name on a local API
     * instance.
     *
     * Berries can be soft or hard. Check out Bulbapedia for greater detail.
     */
    fun firmnessList(
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
    ): PaginatedBerryFirmnessSummaryList {
        return dev.octri.demo.pokeapiUnofficialSdk.methods.Berries.berryFirmnessList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )
    }

    /**
     * Lists berry firmness categories, which describe how soft or hard berries are. Use `limit` and
     * `offset` to select a result window, and `q` to filter categories by name on a local API
     * instance.
     *
     * Berries can be soft or hard. Check out Bulbapedia for greater detail.
     */
    fun firmnessListPaginated(
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
        yieldFn: (BerryFirmnessSummary) -> Boolean,
    ) {
        dev.octri.demo.pokeapiUnofficialSdk.methods.Berries.berryFirmnessListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )
    }

    /**
     * Retrieves a berry firmness category and the berries assigned to it. Supply the category's
     * `id` as a string or integer to look up its associated berry list and localized names.
     *
     * Berries can be soft or hard. Check out Bulbapedia for greater detail.
     */
    fun firmnessRetrieve(id: String, options: RequestOptions? = null): BerryFirmnessDetail {
        return dev.octri.demo.pokeapiUnofficialSdk.methods.Berries.berryFirmnessRetrieve(
            clientConfig,
            id,
            options,
        )
    }

    /**
     * Lists berry flavors, which determine whether a Pokémon benefits or suffers from eating a
     * berry based on its nature. Use `limit` and `offset` to select a result window, and `q` to
     * filter flavors by name on a local API instance.
     *
     * Flavors determine whether a Pokémon will benefit or suffer from eating a berry based on their
     * **nature**. Check out Bulbapedia for greater detail.
     */
    fun flavorList(
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
    ): PaginatedBerryFlavorSummaryList {
        return dev.octri.demo.pokeapiUnofficialSdk.methods.Berries.berryFlavorList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )
    }

    /**
     * Lists berry flavors, which determine whether a Pokémon benefits or suffers from eating a
     * berry based on its nature. Use `limit` and `offset` to select a result window, and `q` to
     * filter flavors by name on a local API instance.
     *
     * Flavors determine whether a Pokémon will benefit or suffer from eating a berry based on their
     * **nature**. Check out Bulbapedia for greater detail.
     */
    fun flavorListPaginated(
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
        yieldFn: (BerryFlavorSummary) -> Boolean,
    ) {
        dev.octri.demo.pokeapiUnofficialSdk.methods.Berries.berryFlavorListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )
    }

    /**
     * Retrieves a berry flavor and the berries associated with it, including their flavor potency.
     * Supply the flavor's `id` as a string or integer to look up its contest type and localized
     * names.
     *
     * Flavors determine whether a Pokémon will benefit or suffer from eating a berry based on their
     * **nature**. Check out Bulbapedia for greater detail.
     */
    fun flavorRetrieve(id: String, options: RequestOptions? = null): BerryFlavorDetail {
        return dev.octri.demo.pokeapiUnofficialSdk.methods.Berries.berryFlavorRetrieve(
            clientConfig,
            id,
            options,
        )
    }
}
