// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dev.octri.demo.pokeapiUnofficialSdk

typealias AbilityChange = dev.octri.demo.pokeapiUnofficialSdk.models.AbilityChange

typealias AbilityChangeEffectText = dev.octri.demo.pokeapiUnofficialSdk.models.AbilityChangeEffectText

typealias AbilityDetail = dev.octri.demo.pokeapiUnofficialSdk.models.AbilityDetail

typealias AbilityEffectText = dev.octri.demo.pokeapiUnofficialSdk.models.AbilityEffectText

typealias AbilityFlavorText = dev.octri.demo.pokeapiUnofficialSdk.models.AbilityFlavorText

typealias AbilityName = dev.octri.demo.pokeapiUnofficialSdk.models.AbilityName

typealias AbilityPokemonDetail = dev.octri.demo.pokeapiUnofficialSdk.models.AbilityPokemonDetail

typealias AbilitySummary = dev.octri.demo.pokeapiUnofficialSdk.models.AbilitySummary

typealias BerryDetail = dev.octri.demo.pokeapiUnofficialSdk.models.BerryDetail

typealias BerryFirmnessDetail = dev.octri.demo.pokeapiUnofficialSdk.models.BerryFirmnessDetail

typealias BerryFirmnessName = dev.octri.demo.pokeapiUnofficialSdk.models.BerryFirmnessName

typealias BerryFirmnessSummary = dev.octri.demo.pokeapiUnofficialSdk.models.BerryFirmnessSummary

typealias BerryFlavorBerryMap = dev.octri.demo.pokeapiUnofficialSdk.models.BerryFlavorBerryMap

typealias BerryFlavorDetail = dev.octri.demo.pokeapiUnofficialSdk.models.BerryFlavorDetail

typealias BerryFlavorMap = dev.octri.demo.pokeapiUnofficialSdk.models.BerryFlavorMap

typealias BerryFlavorName = dev.octri.demo.pokeapiUnofficialSdk.models.BerryFlavorName

typealias BerryFlavorSummary = dev.octri.demo.pokeapiUnofficialSdk.models.BerryFlavorSummary

typealias BerrySummary = dev.octri.demo.pokeapiUnofficialSdk.models.BerrySummary

typealias CharacteristicDescription = dev.octri.demo.pokeapiUnofficialSdk.models.CharacteristicDescription

typealias CharacteristicDetail = dev.octri.demo.pokeapiUnofficialSdk.models.CharacteristicDetail

typealias CharacteristicSummary = dev.octri.demo.pokeapiUnofficialSdk.models.CharacteristicSummary

typealias ContestEffectDetail = dev.octri.demo.pokeapiUnofficialSdk.models.ContestEffectDetail

typealias ContestEffectEffectText = dev.octri.demo.pokeapiUnofficialSdk.models.ContestEffectEffectText

typealias ContestEffectFlavorText = dev.octri.demo.pokeapiUnofficialSdk.models.ContestEffectFlavorText

typealias ContestEffectSummary = dev.octri.demo.pokeapiUnofficialSdk.models.ContestEffectSummary

typealias ContestTypeDetail = dev.octri.demo.pokeapiUnofficialSdk.models.ContestTypeDetail

typealias ContestTypeName = dev.octri.demo.pokeapiUnofficialSdk.models.ContestTypeName

typealias ContestTypeSummary = dev.octri.demo.pokeapiUnofficialSdk.models.ContestTypeSummary

typealias CurrencyDetail = dev.octri.demo.pokeapiUnofficialSdk.models.CurrencyDetail

typealias CurrencyName = dev.octri.demo.pokeapiUnofficialSdk.models.CurrencyName

typealias CurrencySummary = dev.octri.demo.pokeapiUnofficialSdk.models.CurrencySummary

typealias EggGroupDetail = dev.octri.demo.pokeapiUnofficialSdk.models.EggGroupDetail

typealias EggGroupName = dev.octri.demo.pokeapiUnofficialSdk.models.EggGroupName

typealias EggGroupSummary = dev.octri.demo.pokeapiUnofficialSdk.models.EggGroupSummary

typealias EncounterConditionDetail = dev.octri.demo.pokeapiUnofficialSdk.models.EncounterConditionDetail

typealias EncounterConditionName = dev.octri.demo.pokeapiUnofficialSdk.models.EncounterConditionName

typealias EncounterConditionSummary = dev.octri.demo.pokeapiUnofficialSdk.models.EncounterConditionSummary

typealias EncounterConditionValueDetail = dev.octri.demo.pokeapiUnofficialSdk.models.EncounterConditionValueDetail

typealias EncounterConditionValueName = dev.octri.demo.pokeapiUnofficialSdk.models.EncounterConditionValueName

typealias EncounterConditionValueSummary = dev.octri.demo.pokeapiUnofficialSdk.models.EncounterConditionValueSummary

typealias EncounterMethodDetail = dev.octri.demo.pokeapiUnofficialSdk.models.EncounterMethodDetail

typealias EncounterMethodName = dev.octri.demo.pokeapiUnofficialSdk.models.EncounterMethodName

typealias EncounterMethodSummary = dev.octri.demo.pokeapiUnofficialSdk.models.EncounterMethodSummary

typealias EncounterPokemonDetail = dev.octri.demo.pokeapiUnofficialSdk.models.EncounterPokemonDetail

typealias EvolutionChainDetail = dev.octri.demo.pokeapiUnofficialSdk.models.EvolutionChainDetail

typealias EvolutionChainLink = dev.octri.demo.pokeapiUnofficialSdk.models.EvolutionChainLink

typealias EvolutionChainSummary = dev.octri.demo.pokeapiUnofficialSdk.models.EvolutionChainSummary

typealias EvolutionConditionExpression = dev.octri.demo.pokeapiUnofficialSdk.models.EvolutionConditionExpression

typealias EvolutionTriggerDetail = dev.octri.demo.pokeapiUnofficialSdk.models.EvolutionTriggerDetail

typealias EvolutionTriggerName = dev.octri.demo.pokeapiUnofficialSdk.models.EvolutionTriggerName

typealias EvolutionTriggerSummary = dev.octri.demo.pokeapiUnofficialSdk.models.EvolutionTriggerSummary

typealias EvolutionVariableDescription = dev.octri.demo.pokeapiUnofficialSdk.models.EvolutionVariableDescription

typealias EvolutionVariableDetail = dev.octri.demo.pokeapiUnofficialSdk.models.EvolutionVariableDetail

typealias EvolutionVariableName = dev.octri.demo.pokeapiUnofficialSdk.models.EvolutionVariableName

typealias EvolutionVariableSummary = dev.octri.demo.pokeapiUnofficialSdk.models.EvolutionVariableSummary

typealias Experience = dev.octri.demo.pokeapiUnofficialSdk.models.Experience

typealias GenderDetail = dev.octri.demo.pokeapiUnofficialSdk.models.GenderDetail

typealias GenderPokemonSpecies = dev.octri.demo.pokeapiUnofficialSdk.models.GenderPokemonSpecies

typealias GenderSummary = dev.octri.demo.pokeapiUnofficialSdk.models.GenderSummary

typealias GenerationDetail = dev.octri.demo.pokeapiUnofficialSdk.models.GenerationDetail

typealias GenerationName = dev.octri.demo.pokeapiUnofficialSdk.models.GenerationName

typealias GenerationSummary = dev.octri.demo.pokeapiUnofficialSdk.models.GenerationSummary

typealias GrowthRateDescription = dev.octri.demo.pokeapiUnofficialSdk.models.GrowthRateDescription

typealias GrowthRateDetail = dev.octri.demo.pokeapiUnofficialSdk.models.GrowthRateDetail

typealias GrowthRateSummary = dev.octri.demo.pokeapiUnofficialSdk.models.GrowthRateSummary

typealias ItemAttributeDescription = dev.octri.demo.pokeapiUnofficialSdk.models.ItemAttributeDescription

typealias ItemAttributeDetail = dev.octri.demo.pokeapiUnofficialSdk.models.ItemAttributeDetail

typealias ItemAttributeName = dev.octri.demo.pokeapiUnofficialSdk.models.ItemAttributeName

typealias ItemAttributeSummary = dev.octri.demo.pokeapiUnofficialSdk.models.ItemAttributeSummary

typealias ItemCategoryDetail = dev.octri.demo.pokeapiUnofficialSdk.models.ItemCategoryDetail

typealias ItemCategoryName = dev.octri.demo.pokeapiUnofficialSdk.models.ItemCategoryName

typealias ItemCategorySummary = dev.octri.demo.pokeapiUnofficialSdk.models.ItemCategorySummary

typealias ItemDetail = dev.octri.demo.pokeapiUnofficialSdk.models.ItemDetail

typealias ItemEffectText = dev.octri.demo.pokeapiUnofficialSdk.models.ItemEffectText

typealias ItemFlavorText = dev.octri.demo.pokeapiUnofficialSdk.models.ItemFlavorText

typealias ItemFlingEffectDetail = dev.octri.demo.pokeapiUnofficialSdk.models.ItemFlingEffectDetail

typealias ItemFlingEffectEffectText = dev.octri.demo.pokeapiUnofficialSdk.models.ItemFlingEffectEffectText

typealias ItemFlingEffectSummary = dev.octri.demo.pokeapiUnofficialSdk.models.ItemFlingEffectSummary

typealias ItemGameIndex = dev.octri.demo.pokeapiUnofficialSdk.models.ItemGameIndex

typealias ItemMachine = dev.octri.demo.pokeapiUnofficialSdk.models.ItemMachine

typealias ItemName = dev.octri.demo.pokeapiUnofficialSdk.models.ItemName

typealias ItemPocketDetail = dev.octri.demo.pokeapiUnofficialSdk.models.ItemPocketDetail

typealias ItemPocketName = dev.octri.demo.pokeapiUnofficialSdk.models.ItemPocketName

typealias ItemPocketSummary = dev.octri.demo.pokeapiUnofficialSdk.models.ItemPocketSummary

typealias ItemPrice = dev.octri.demo.pokeapiUnofficialSdk.models.ItemPrice

typealias ItemSprites = dev.octri.demo.pokeapiUnofficialSdk.models.ItemSprites

typealias ItemSummary = dev.octri.demo.pokeapiUnofficialSdk.models.ItemSummary

typealias LanguageDetail = dev.octri.demo.pokeapiUnofficialSdk.models.LanguageDetail

typealias LanguageName = dev.octri.demo.pokeapiUnofficialSdk.models.LanguageName

typealias LanguageSummary = dev.octri.demo.pokeapiUnofficialSdk.models.LanguageSummary

typealias LocationAreaDetail = dev.octri.demo.pokeapiUnofficialSdk.models.LocationAreaDetail

typealias LocationAreaEncounterDetail = dev.octri.demo.pokeapiUnofficialSdk.models.LocationAreaEncounterDetail

typealias LocationAreaEncounterRate = dev.octri.demo.pokeapiUnofficialSdk.models.LocationAreaEncounterRate

typealias LocationAreaEncounterVersionDetail = dev.octri.demo.pokeapiUnofficialSdk.models.LocationAreaEncounterVersionDetail

typealias LocationAreaName = dev.octri.demo.pokeapiUnofficialSdk.models.LocationAreaName

typealias LocationAreaPokemonEncounter = dev.octri.demo.pokeapiUnofficialSdk.models.LocationAreaPokemonEncounter

typealias LocationAreaPokemonEncounterVersion = dev.octri.demo.pokeapiUnofficialSdk.models.LocationAreaPokemonEncounterVersion

typealias LocationAreaSummary = dev.octri.demo.pokeapiUnofficialSdk.models.LocationAreaSummary

typealias LocationDetail = dev.octri.demo.pokeapiUnofficialSdk.models.LocationDetail

typealias LocationGameIndex = dev.octri.demo.pokeapiUnofficialSdk.models.LocationGameIndex

typealias LocationName = dev.octri.demo.pokeapiUnofficialSdk.models.LocationName

typealias LocationSummary = dev.octri.demo.pokeapiUnofficialSdk.models.LocationSummary

typealias MachineDetail = dev.octri.demo.pokeapiUnofficialSdk.models.MachineDetail

typealias MachineSummary = dev.octri.demo.pokeapiUnofficialSdk.models.MachineSummary

typealias MoveBattleStyleDetail = dev.octri.demo.pokeapiUnofficialSdk.models.MoveBattleStyleDetail

typealias MoveBattleStyleName = dev.octri.demo.pokeapiUnofficialSdk.models.MoveBattleStyleName

typealias MoveBattleStyleSummary = dev.octri.demo.pokeapiUnofficialSdk.models.MoveBattleStyleSummary

typealias MoveChange = dev.octri.demo.pokeapiUnofficialSdk.models.MoveChange

typealias MoveCombos = dev.octri.demo.pokeapiUnofficialSdk.models.MoveCombos

typealias MoveComboUsage = dev.octri.demo.pokeapiUnofficialSdk.models.MoveComboUsage

typealias MoveDamageClassDescription = dev.octri.demo.pokeapiUnofficialSdk.models.MoveDamageClassDescription

typealias MoveDamageClassDetail = dev.octri.demo.pokeapiUnofficialSdk.models.MoveDamageClassDetail

typealias MoveDamageClassName = dev.octri.demo.pokeapiUnofficialSdk.models.MoveDamageClassName

typealias MoveDamageClassSummary = dev.octri.demo.pokeapiUnofficialSdk.models.MoveDamageClassSummary

typealias MoveDetail = dev.octri.demo.pokeapiUnofficialSdk.models.MoveDetail

typealias MoveEffectChange = dev.octri.demo.pokeapiUnofficialSdk.models.MoveEffectChange

typealias MoveEffectChangeEffectText = dev.octri.demo.pokeapiUnofficialSdk.models.MoveEffectChangeEffectText

typealias MoveEffectEffectText = dev.octri.demo.pokeapiUnofficialSdk.models.MoveEffectEffectText

typealias MoveFlavorText = dev.octri.demo.pokeapiUnofficialSdk.models.MoveFlavorText

typealias MoveLearnMethodDescription = dev.octri.demo.pokeapiUnofficialSdk.models.MoveLearnMethodDescription

typealias MoveLearnMethodDetail = dev.octri.demo.pokeapiUnofficialSdk.models.MoveLearnMethodDetail

typealias MoveLearnMethodName = dev.octri.demo.pokeapiUnofficialSdk.models.MoveLearnMethodName

typealias MoveLearnMethodSummary = dev.octri.demo.pokeapiUnofficialSdk.models.MoveLearnMethodSummary

typealias MoveMeta = dev.octri.demo.pokeapiUnofficialSdk.models.MoveMeta

typealias MoveMetaAilmentDetail = dev.octri.demo.pokeapiUnofficialSdk.models.MoveMetaAilmentDetail

typealias MoveMetaAilmentName = dev.octri.demo.pokeapiUnofficialSdk.models.MoveMetaAilmentName

typealias MoveMetaAilmentSummary = dev.octri.demo.pokeapiUnofficialSdk.models.MoveMetaAilmentSummary

typealias MoveMetaCategoryDescription = dev.octri.demo.pokeapiUnofficialSdk.models.MoveMetaCategoryDescription

typealias MoveMetaCategoryDetail = dev.octri.demo.pokeapiUnofficialSdk.models.MoveMetaCategoryDetail

typealias MoveMetaCategorySummary = dev.octri.demo.pokeapiUnofficialSdk.models.MoveMetaCategorySummary

typealias MoveMetaStatChange = dev.octri.demo.pokeapiUnofficialSdk.models.MoveMetaStatChange

typealias MoveName = dev.octri.demo.pokeapiUnofficialSdk.models.MoveName

typealias MoveStatChange = dev.octri.demo.pokeapiUnofficialSdk.models.MoveStatChange

typealias MoveSummary = dev.octri.demo.pokeapiUnofficialSdk.models.MoveSummary

typealias MoveTargetDescription = dev.octri.demo.pokeapiUnofficialSdk.models.MoveTargetDescription

typealias MoveTargetDetail = dev.octri.demo.pokeapiUnofficialSdk.models.MoveTargetDetail

typealias MoveTargetName = dev.octri.demo.pokeapiUnofficialSdk.models.MoveTargetName

typealias MoveTargetSummary = dev.octri.demo.pokeapiUnofficialSdk.models.MoveTargetSummary

typealias NatureBattleStylePreference = dev.octri.demo.pokeapiUnofficialSdk.models.NatureBattleStylePreference

typealias NatureDetail = dev.octri.demo.pokeapiUnofficialSdk.models.NatureDetail

typealias NatureName = dev.octri.demo.pokeapiUnofficialSdk.models.NatureName

typealias NaturePokeathlonStat = dev.octri.demo.pokeapiUnofficialSdk.models.NaturePokeathlonStat

typealias NatureSummary = dev.octri.demo.pokeapiUnofficialSdk.models.NatureSummary

typealias PaginatedAbilitySummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedAbilitySummaryList

typealias PaginatedBerryFirmnessSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedBerryFirmnessSummaryList

typealias PaginatedBerryFlavorSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedBerryFlavorSummaryList

typealias PaginatedBerrySummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedBerrySummaryList

typealias PaginatedCharacteristicSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedCharacteristicSummaryList

typealias PaginatedContestEffectSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedContestEffectSummaryList

typealias PaginatedContestTypeSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedContestTypeSummaryList

typealias PaginatedCurrencySummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedCurrencySummaryList

typealias PaginatedEggGroupSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedEggGroupSummaryList

typealias PaginatedEncounterConditionSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedEncounterConditionSummaryList

typealias PaginatedEncounterConditionValueSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedEncounterConditionValueSummaryList

typealias PaginatedEncounterMethodSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedEncounterMethodSummaryList

typealias PaginatedEvolutionChainSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedEvolutionChainSummaryList

typealias PaginatedEvolutionTriggerSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedEvolutionTriggerSummaryList

typealias PaginatedEvolutionVariableSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedEvolutionVariableSummaryList

typealias PaginatedGenderSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedGenderSummaryList

typealias PaginatedGenerationSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedGenerationSummaryList

typealias PaginatedGrowthRateSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedGrowthRateSummaryList

typealias PaginatedItemAttributeSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedItemAttributeSummaryList

typealias PaginatedItemCategorySummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedItemCategorySummaryList

typealias PaginatedItemFlingEffectSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedItemFlingEffectSummaryList

typealias PaginatedItemPocketSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedItemPocketSummaryList

typealias PaginatedItemSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedItemSummaryList

typealias PaginatedLanguageSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedLanguageSummaryList

typealias PaginatedLocationAreaSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedLocationAreaSummaryList

typealias PaginatedLocationSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedLocationSummaryList

typealias PaginatedMachineSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedMachineSummaryList

typealias PaginatedMoveBattleStyleSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedMoveBattleStyleSummaryList

typealias PaginatedMoveDamageClassSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedMoveDamageClassSummaryList

typealias PaginatedMoveLearnMethodSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedMoveLearnMethodSummaryList

typealias PaginatedMoveMetaAilmentSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedMoveMetaAilmentSummaryList

typealias PaginatedMoveMetaCategorySummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedMoveMetaCategorySummaryList

typealias PaginatedMoveSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedMoveSummaryList

typealias PaginatedMoveTargetSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedMoveTargetSummaryList

typealias PaginatedNatureSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedNatureSummaryList

typealias PaginatedPalParkAreaSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedPalParkAreaSummaryList

typealias PaginatedPokeathlonStatSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedPokeathlonStatSummaryList

typealias PaginatedPokedexSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedPokedexSummaryList

typealias PaginatedPokemonColorSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedPokemonColorSummaryList

typealias PaginatedPokemonFormSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedPokemonFormSummaryList

typealias PaginatedPokemonHabitatSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedPokemonHabitatSummaryList

typealias PaginatedPokemonShapeSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedPokemonShapeSummaryList

typealias PaginatedPokemonSpeciesSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedPokemonSpeciesSummaryList

typealias PaginatedPokemonSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedPokemonSummaryList

typealias PaginatedRegionSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedRegionSummaryList

typealias PaginatedStatSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedStatSummaryList

typealias PaginatedSuperContestEffectSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedSuperContestEffectSummaryList

typealias PaginatedTypeSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedTypeSummaryList

typealias PaginatedVersionGroupSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedVersionGroupSummaryList

typealias PaginatedVersionSummaryList = dev.octri.demo.pokeapiUnofficialSdk.models.PaginatedVersionSummaryList

typealias PalParkAreaDetail = dev.octri.demo.pokeapiUnofficialSdk.models.PalParkAreaDetail

typealias PalParkAreaName = dev.octri.demo.pokeapiUnofficialSdk.models.PalParkAreaName

typealias PalParkAreaSummary = dev.octri.demo.pokeapiUnofficialSdk.models.PalParkAreaSummary

typealias PalParkEncounter = dev.octri.demo.pokeapiUnofficialSdk.models.PalParkEncounter

typealias PokeapiMetaResponse = dev.octri.demo.pokeapiUnofficialSdk.models.PokeapiMetaResponse

typealias PokeathlonStatAffectingNature = dev.octri.demo.pokeapiUnofficialSdk.models.PokeathlonStatAffectingNature

typealias PokeathlonStatAffectingNatures = dev.octri.demo.pokeapiUnofficialSdk.models.PokeathlonStatAffectingNatures

typealias PokeathlonStatDetail = dev.octri.demo.pokeapiUnofficialSdk.models.PokeathlonStatDetail

typealias PokeathlonStatName = dev.octri.demo.pokeapiUnofficialSdk.models.PokeathlonStatName

typealias PokeathlonStatSummary = dev.octri.demo.pokeapiUnofficialSdk.models.PokeathlonStatSummary

typealias PokedexDescription = dev.octri.demo.pokeapiUnofficialSdk.models.PokedexDescription

typealias PokedexDetail = dev.octri.demo.pokeapiUnofficialSdk.models.PokedexDetail

typealias PokedexName = dev.octri.demo.pokeapiUnofficialSdk.models.PokedexName

typealias PokedexSummary = dev.octri.demo.pokeapiUnofficialSdk.models.PokedexSummary

typealias PokemonAbility = dev.octri.demo.pokeapiUnofficialSdk.models.PokemonAbility

typealias PokemonAbilityPast = dev.octri.demo.pokeapiUnofficialSdk.models.PokemonAbilityPast

typealias PokemonColorDetail = dev.octri.demo.pokeapiUnofficialSdk.models.PokemonColorDetail

typealias PokemonColorName = dev.octri.demo.pokeapiUnofficialSdk.models.PokemonColorName

typealias PokemonColorSummary = dev.octri.demo.pokeapiUnofficialSdk.models.PokemonColorSummary

typealias PokemonCries = dev.octri.demo.pokeapiUnofficialSdk.models.PokemonCries

typealias PokemonDetail = dev.octri.demo.pokeapiUnofficialSdk.models.PokemonDetail

typealias PokemonDexEntry = dev.octri.demo.pokeapiUnofficialSdk.models.PokemonDexEntry

typealias PokemonDexNumber = dev.octri.demo.pokeapiUnofficialSdk.models.PokemonDexNumber

typealias PokemonEncounterDetailResponse = dev.octri.demo.pokeapiUnofficialSdk.models.PokemonEncounterDetailResponse
