// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dev.octri.demo.pokeapiUnofficialSdk

import java.time.Duration
import java.util.LinkedHashMap

private const val DEFAULT_MAX_ATTEMPTS = 3
private val DEFAULT_RETRY_STATUSES = listOf(408, 425, 429, 500, 502, 503, 504)
private const val DEFAULT_BACKOFF_MILLIS = 500L
private const val DEFAULT_MAX_BACKOFF_MILLIS = 8000L
private const val DEFAULT_TIMEOUT_MILLIS = 30000L
private val PII_KEYS = setOf("authorization", "cookie", "set_cookie", "setcookie", "password", "passcode", "secret", "token", "api_key", "apikey", "access_token", "accesstoken", "refresh_token", "refreshtoken", "client_secret", "clientsecret", "email", "email_address", "emailaddress", "phone", "phone_number", "phonenumber", "address", "street_address", "streetaddress", "street", "city", "postal_code", "postalcode", "zip_code", "zipcode", "first_name", "firstname", "last_name", "lastname", "full_name", "fullname", "username", "user_name", "ip", "ip_address", "ipaddress", "user_agent", "useragent", "referrer", "url", "uri", "query", "latitude", "longitude", "ssn", "social_security_number", "socialsecuritynumber", "tax_id", "taxid", "national_id", "nationalid", "passport_number", "passportnumber", "date_of_birth", "dateofbirth", "birth_date", "birthdate", "headers", "body", "request_headers", "requestheaders", "request_body", "requestbody")
/** Word runs matched anywhere inside a key (`billingEmail`, `stripe_secret_key`). */
private val PII_SEGMENTS = listOf("_password_", "_passwd_", "_passphrase_", "_secret_", "_token_", "_api_key_", "_access_token_", "_refresh_token_", "_client_secret_", "_authorization_", "_cookie_", "_set_cookie_", "_credential_", "_private_key_", "_access_key_", "_session_id_", "_card_number_", "_credit_card_", "_cvv_", "_cvc_", "_email_", "_email_address_", "_phone_", "_phone_number_", "_address_", "_street_address_", "_postal_code_", "_zip_code_", "_first_name_", "_last_name_", "_full_name_", "_user_name_", "_user_agent_", "_ssn_", "_social_security_number_", "_tax_id_", "_national_id_", "_passport_number_", "_passport_", "_date_of_birth_", "_birth_date_", "_birthdate_", "_dob_")
private const val PII_REDACTION_MARKER = "[REDACTED]"

/** `stripeSecretKey`, `API-Key` and `first name` become `stripe_secret_key`, `api_key`, `first_name`. */
private fun normalizePiiKey(key: Any?): String {
    val out = StringBuilder()
    var previous = ' '
    for (char in key.toString()) {
        if (char.isUpperCase() && (previous.isLowerCase() || previous.isDigit())) out.append('_')
        out.append(if (char.isLetterOrDigit()) char.lowercaseChar() else '_')
        previous = char
    }
    return out.toString()
}

private fun isPiiKey(key: Any?): Boolean {
    val normalized = normalizePiiKey(key)
    if (PII_KEYS.contains(normalized)) return true
    val padded = "_" + normalized + "_"
    return PII_SEGMENTS.any { segment -> padded.contains(segment) }
}

/** Recursively redacts common credential and direct-identifier fields. */
internal fun sanitizeTelemetry(value: Any?, enabled: Boolean): Any? {
    if (!enabled || value == null) return value
    return when (value) {
        is Map<*, *> -> LinkedHashMap<String, Any?>().also { output ->
            value.forEach { (key, item) ->
                val name = key.toString()
                output[name] = if (isPiiKey(key)) {
                    PII_REDACTION_MARKER
                } else {
                    sanitizeTelemetry(item, enabled)
                }
            }
        }
        is List<*> -> value.map { item -> sanitizeTelemetry(item, enabled) }
        is Array<*> -> value.map { item -> sanitizeTelemetry(item, enabled) }
        else -> value
    }
}

data class ClientAuthConfig(
    /** Arbitrary headers added to every request (e.g., custom API version headers). */
    var headers: Map<String, String>? = null,
)


/**
 * Error reporting. The endpoint/key/environment below are baked in from the
 * dashboard monitoring config, but [enabled] is false at rest — this SDK reports
 * nothing until the consumer opts in, either by constructing the client with
 * `logging = LoggingConfig(enabled = true)` or by calling `setLoggingConfig(...)`.
 */
data class LoggingConfig(
    /** When true, request errors are sent to [endpoint]. */
    var enabled: Boolean = false,
    /** HTTP endpoint that receives error payloads as JSON POST requests. */
    var endpoint: String? = null,
    /** Optional bearer token used when posting to the logging endpoint. */
    var apiKey: String? = null,
    /** Enrichment forwarded with every logged event. */
    var environment: String? = null,
    var release: String? = null,
    var user: Map<String, Any?>? = null,
    var tags: Map<String, Any?>? = null,
    /** Redact common credentials and direct identifiers before telemetry (default true). */
    var filterPii: Boolean = true,
)

data class RetryConfig(
    var maxAttempts: Int = DEFAULT_MAX_ATTEMPTS,
    var retryOn: List<Int> = DEFAULT_RETRY_STATUSES,
    var backoff: Duration = Duration.ofMillis(DEFAULT_BACKOFF_MILLIS),
    var maxBackoff: Duration = Duration.ofMillis(DEFAULT_MAX_BACKOFF_MILLIS),
)

/** Controls Idempotency-Key generation, so a retried write is not executed twice. */
data class IdempotencyConfig(
    var enabled: Boolean = true,
    var headerName: String = "Idempotency-Key",
    var methods: List<String> = listOf("POST", "PATCH"),
)

/**
 * Per-call options every generated operation accepts. Each set field applies
 * to that call only, over the client config. Streaming operations apply only
 * [headers].
 */
data class RequestOptions(
    /** Merged over the auth and operation headers for this call. */
    val headers: Map<String, String> = emptyMap(),
    /** Replaces the generated Idempotency-Key; an empty key sends none. */
    val idempotencyKey: String? = null,
    /** Replaces the client retry policy. */
    val retry: RetryConfig? = null,
    /** Replaces the client per-attempt timeout. */
    val timeout: Duration? = null,
)

/**
 * A single in-flight HTTP attempt as seen by middleware. Mutate [headers] or
 * [body] to alter the request before it hits the wire. [meta] is a free-form
 * map middleware can use to share state across the chain.
 */
data class SdkRequest(
    var method: String,
    var url: String,
    var headers: MutableMap<String, String>,
    var body: String?,
    // Raw body bytes (multipart/form-data, octet-stream); takes precedence over
    // `body` when set so binary content is sent without lossy String round-trips.
    var bodyBytes: ByteArray? = null,
    var contentType: String,
    var operationId: String,
    var attempt: Int,
    var meta: MutableMap<String, Any?> = mutableMapOf(),
)

/** Raw response visible to middleware. Body bytes are never pre-decoded. */
data class SdkRawResponse(
    val statusCode: Int,
    val statusText: String,
    val headers: Map<String, String>,
    val body: ByteArray,
    val requestId: String?,
    val latency: Duration,
    val attempt: Int,
)

/** Innermost continuation in a middleware chain. */
typealias SdkNext = (SdkRequest) -> SdkRawResponse

/**
 * User-supplied request interceptor. Runs once per HTTP attempt — retries
 * pass through the chain N times. Compose logging, tracing, caching, etc.
 * without forking the generator.
 *
 * ```
 * val logging: Middleware = { req, next ->
 *     val resp = next(req)
 *     println("${req.method} ${req.url} -> ${resp.statusCode}")
 *     resp
 * }
 * ```
 */
typealias Middleware = (SdkRequest, SdkNext) -> SdkRawResponse

data class ClientConfig(
    var baseUrl: String? = null,
    var auth: ClientAuthConfig? = null,
    var logging: LoggingConfig = LoggingConfig(),
    var retry: RetryConfig = RetryConfig(),
    var idempotency: IdempotencyConfig = IdempotencyConfig(),
    var timeout: Duration = Duration.ofMillis(DEFAULT_TIMEOUT_MILLIS),
    var onResponse: ((SdkResponse<Any?>) -> Unit)? = null,
    /**
     * Middleware chain. Replaced wholesale on configure(); to extend, read
     * the current value and pass a list including the previous entries.
     */
    var middleware: List<Middleware> = emptyList(),
)

object SdkConfig {
    private var config: ClientConfig = ClientConfig(baseUrl = "https://pokeapi.co")

    /**
     * Configures the SDK client. Non-null fields on the supplied config are
     * merged into the existing configuration.
     */
    fun configure(config: ClientConfig? = null): ClientConfig {
        config?.let { cfg ->
            cfg.baseUrl?.let { this.config.baseUrl = it }
            cfg.auth?.let { this.config.auth = it }
            this.config.logging = cfg.logging
            this.config.retry = cfg.retry
            this.config.idempotency = cfg.idempotency
            this.config.timeout = cfg.timeout
            cfg.onResponse?.let { this.config.onResponse = it }
            if (cfg.middleware.isNotEmpty()) this.config.middleware = cfg.middleware
        }
        return this.config
    }

    /** Returns the current [ClientConfig]. */
    fun getConfig(): ClientConfig = config

    /**
     * Turns SDK logging on and configures it in one call.
     *
     * Logging is OFF by default — this SDK reports nothing until you ask it to.
     * There are exactly two ways to turn it on:
     * ```
     * SdkConfig.configure(ClientConfig(logging = LoggingConfig(enabled = true)))
     * SdkConfig.setLoggingConfig { environment = "production" }
     * ```
     * Reports go to the endpoint this build was generated with, or to the
     * `endpoint` you set; with neither, nothing is sent. Set `enabled = false` in
     * the block to turn logging back off.
     */
    fun setLoggingConfig(block: LoggingConfig.() -> Unit = {}): LoggingConfig {
        // Opting in IS the point of this call, so enabled flips to true before the
        // block runs — a block that sets `enabled = false` still wins, making this
        // the off switch too.
        config.logging.enabled = true
        config.logging.block()
        return config.logging
    }
}
