// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dev.octri.demo.pokeapiUnofficialSdk


class UtilityNamespace(private val clientConfig: ClientConfig) {
    /**
     * Returns metadata about the currently deployed API version. Use the `deploy_date`, `hash`, and `tag` fields to identify the deployment; each value can be null.
     *
     * Returns metadata about the current deployed version of the API, including the git commit hash, deploy date, and tag (if any).
     */
    fun metaRetrieve(options: RequestOptions? = null): PokeapiMetaResponse {
        return dev.octri.demo.pokeapiUnofficialSdk.methods.Utility.metaRetrieve(clientConfig, options)
    }

    /**
     * Lists languages used for translations of API resource information. Use `limit` and `offset` to control the result page, or `q` to filter languages by name with a case-insensitive query.
     *
     * Languages for translations of API resource information.
     */
    fun languageList(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedLanguageSummaryList {
        return dev.octri.demo.pokeapiUnofficialSdk.methods.Utility.languageList(clientConfig, limit, offset, q, options)
    }

    /**
     * Lists languages used for translations of API resource information. Use `limit` and `offset` to control the result page, or `q` to filter languages by name with a case-insensitive query.
     *
     * Languages for translations of API resource information.
     */
    fun languageListPaginated(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (LanguageSummary) -> Boolean) {
        dev.octri.demo.pokeapiUnofficialSdk.methods.Utility.languageListPaginated(clientConfig, limit, offset, q, options, yieldFn)
    }

    /**
     * Retrieves a single language used for translations of API resource information. Use `id` to identify the language whose official status, ISO codes, and localized names you want to inspect.
     *
     * Languages for translations of API resource information.
     */
    fun languageRetrieve(id: String, options: RequestOptions? = null): LanguageDetail {
        return dev.octri.demo.pokeapiUnofficialSdk.methods.Utility.languageRetrieve(clientConfig, id, options)
    }

}
