// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk


class EncountersNamespace(private val clientConfig: ClientConfig) {
    /**
     * Lists methods by which players can encounter Pokémon in the wild, such as walking through tall grass. Use `limit` and `offset` to control the result page, or filter by name with the locally available, case-insensitive `q` query.
     *
     * Methods by which the player might can encounter Pokémon in the wild, e.g., walking in tall grass. Check out Bulbapedia for greater detail.
     */
    fun methodList(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedEncounterMethodSummaryList {
        return sdk.methods.Encounters.encounterMethodList(clientConfig, limit, offset, q, options)
    }

    /**
     * Lists methods by which players can encounter Pokémon in the wild, such as walking through tall grass. Use `limit` and `offset` to control the result page, or filter by name with the locally available, case-insensitive `q` query.
     *
     * Methods by which the player might can encounter Pokémon in the wild, e.g., walking in tall grass. Check out Bulbapedia for greater detail.
     */
    fun methodListPaginated(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (EncounterMethodSummary) -> Boolean) {
        sdk.methods.Encounters.encounterMethodListPaginated(clientConfig, limit, offset, q, options, yieldFn)
    }

    /**
     * Retrieves a method by which players can encounter Pokémon in the wild. Use the `id` path parameter to view its name, optional order value, and localized names.
     *
     * Methods by which the player might can encounter Pokémon in the wild, e.g., walking in tall grass. Check out Bulbapedia for greater detail.
     */
    fun methodRetrieve(id: String, options: RequestOptions? = null): EncounterMethodDetail {
        return sdk.methods.Encounters.encounterMethodRetrieve(clientConfig, id, options)
    }

    /**
     * Lists conditions that affect which Pokémon might appear in the wild, such as the time of day. Use `limit` and `offset` to control the result page, or filter by name with the locally available, case-insensitive `q` query.
     *
     * Conditions which affect what pokemon might appear in the wild, e.g., day or night.
     */
    fun conditionList(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedEncounterConditionSummaryList {
        return sdk.methods.Encounters.encounterConditionList(clientConfig, limit, offset, q, options)
    }

    /**
     * Lists conditions that affect which Pokémon might appear in the wild, such as the time of day. Use `limit` and `offset` to control the result page, or filter by name with the locally available, case-insensitive `q` query.
     *
     * Conditions which affect what pokemon might appear in the wild, e.g., day or night.
     */
    fun conditionListPaginated(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (EncounterConditionSummary) -> Boolean) {
        sdk.methods.Encounters.encounterConditionListPaginated(clientConfig, limit, offset, q, options, yieldFn)
    }

    /**
     * Retrieves a specific encounter condition, such as a time of day that affects which Pokémon may appear in the wild. Use `id` to identify the condition whose values and localized names you need.
     *
     * Conditions which affect what pokemon might appear in the wild, e.g., day or night.
     */
    fun conditionRetrieve(id: String, options: RequestOptions? = null): EncounterConditionDetail {
        return sdk.methods.Encounters.encounterConditionRetrieve(clientConfig, id, options)
    }

    /**
     * Lists encounter condition values, which represent the possible states of an encounter condition, such as day or night. Use `limit` and `offset` to control the result page, or use `q` to search names case-insensitively; `q` is available only on local deployments.
     *
     * Encounter condition values are the various states that an encounter condition can have, i.e., time of day can be either day or night.
     */
    fun conditionValueList(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedEncounterConditionValueSummaryList {
        return sdk.methods.Encounters.encounterConditionValueList(clientConfig, limit, offset, q, options)
    }

    /**
     * Lists encounter condition values, which represent the possible states of an encounter condition, such as day or night. Use `limit` and `offset` to control the result page, or use `q` to search names case-insensitively; `q` is available only on local deployments.
     *
     * Encounter condition values are the various states that an encounter condition can have, i.e., time of day can be either day or night.
     */
    fun conditionValueListPaginated(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (EncounterConditionValueSummary) -> Boolean) {
        sdk.methods.Encounters.encounterConditionValueListPaginated(clientConfig, limit, offset, q, options, yieldFn)
    }

    /**
     * Retrieves a specific encounter condition value, such as the day or night state of an encounter condition. Use `id` to identify the value and retrieve its associated condition and localized names.
     *
     * Encounter condition values are the various states that an encounter condition can have, i.e., time of day can be either day or night.
     */
    fun conditionValueRetrieve(id: String, options: RequestOptions? = null): EncounterConditionValueDetail {
        return sdk.methods.Encounters.encounterConditionValueRetrieve(clientConfig, id, options)
    }

    /**
     * Lists encounter location data for a Pokémon identified by its ID. Use `pokemon_id` to select the Pokémon; the value must contain digits only.
     *
     * Handles Pokemon Encounters as a sub-resource.
     */
    fun pokemonList(pokemonId: String, options: RequestOptions? = null): List<PokemonEncounterResponse> {
        return sdk.methods.Encounters.pokemonEncountersList(clientConfig, pokemonId, options)
    }

}
