// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import com.fasterxml.jackson.core.JsonProcessingException
import com.fasterxml.jackson.core.type.TypeReference
import java.time.Duration

/**
 * Envelope returned by the low-level request layer. High-level endpoint
 * methods unwrap [data] automatically.
 */
data class SdkResponse<T>(
    val data: T,
    val statusCode: Int,
    val headers: Map<String, String>,
    val requestId: String?,
    val latency: Duration,
    val attempt: Int,
)

/**
 * Top-level error type for every SDK failure path. Concrete subclasses:
 * [SdkValidationError], [SdkHttpError], [SdkNetworkError], [SdkTimeoutError].
 */
sealed class SdkError(message: String, cause: Throwable? = null) : RuntimeException(message, cause) {
    /** HTTP status code when produced from an HTTP response, otherwise null. */
    open val statusCode: Int? get() = null
    /** Request id captured from the HTTP response, if any. */
    open val requestId: String? get() = null
}

/** Thrown when a method argument fails an OpenAPI constraint pre-flight. */
class SdkValidationError(
    val field: String,
    val code: String,
    message: String,
    val meta: Map<String, Any?> = emptyMap(),
) : SdkError(message)

/** Thrown for any non-2xx HTTP response. */
open class SdkHttpError(
    override val statusCode: Int,
    val statusText: String,
    val body: ByteArray,
    val headers: Map<String, String>,
    override val requestId: String?,
) : SdkError(sdkHttpErrorMessage(statusCode, statusText, body, headers)) {
    val bodyText: String get() = body.toString(Charsets.UTF_8)

    /**
     * Decodes the body into the model the API declares for this error, on the same terms as a
     * success response. [body] keeps the raw bytes.
     */
    inline fun <reified T> decodeBody(): T =
        try {
            SdkClient.mapper.readValue(body, object : TypeReference<T>() {})
        } catch (error: JsonProcessingException) {
            SdkClient.rethrowModelValidation(error)
        }

    companion object {
        /** Builds the status-specific subclass, or the base class for other statuses. */
        fun forStatus(
            statusCode: Int,
            statusText: String,
            body: ByteArray,
            headers: Map<String, String>,
            requestId: String?,
        ): SdkHttpError {
            val create: SdkHttpErrorFactory =
                if (statusCode >= HTTP_SERVER_ERROR_MIN) {
                    ::SdkInternalServerError
                } else {
                    SDK_STATUS_ERRORS[statusCode] ?: ::SdkHttpError
                }
            return create(statusCode, statusText, body, headers, requestId)
        }
    }
}

/** Thrown for an HTTP 400 response. */
class SdkBadRequestError(
    statusCode: Int,
    statusText: String,
    body: ByteArray,
    headers: Map<String, String>,
    requestId: String?,
) : SdkHttpError(statusCode, statusText, body, headers, requestId)

/** Thrown for an HTTP 401 response. */
class SdkUnauthorizedError(
    statusCode: Int,
    statusText: String,
    body: ByteArray,
    headers: Map<String, String>,
    requestId: String?,
) : SdkHttpError(statusCode, statusText, body, headers, requestId)

/** Thrown for an HTTP 403 response. */
class SdkPermissionDeniedError(
    statusCode: Int,
    statusText: String,
    body: ByteArray,
    headers: Map<String, String>,
    requestId: String?,
) : SdkHttpError(statusCode, statusText, body, headers, requestId)

/** Thrown for an HTTP 404 response. */
class SdkNotFoundError(
    statusCode: Int,
    statusText: String,
    body: ByteArray,
    headers: Map<String, String>,
    requestId: String?,
) : SdkHttpError(statusCode, statusText, body, headers, requestId)

/** Thrown for an HTTP 409 response. */
class SdkConflictError(
    statusCode: Int,
    statusText: String,
    body: ByteArray,
    headers: Map<String, String>,
    requestId: String?,
) : SdkHttpError(statusCode, statusText, body, headers, requestId)

/** Thrown for an HTTP 422 response. */
class SdkUnprocessableEntityError(
    statusCode: Int,
    statusText: String,
    body: ByteArray,
    headers: Map<String, String>,
    requestId: String?,
) : SdkHttpError(statusCode, statusText, body, headers, requestId)

/** Thrown for an HTTP 429 response. */
class SdkRateLimitError(
    statusCode: Int,
    statusText: String,
    body: ByteArray,
    headers: Map<String, String>,
    requestId: String?,
) : SdkHttpError(statusCode, statusText, body, headers, requestId)

/** Thrown for any HTTP 5xx response. */
class SdkInternalServerError(
    statusCode: Int,
    statusText: String,
    body: ByteArray,
    headers: Map<String, String>,
    requestId: String?,
) : SdkHttpError(statusCode, statusText, body, headers, requestId)

private const val SDK_HTTP_ERROR_DETAIL_LIMIT = 512

private const val HTTP_SERVER_ERROR_MIN = 500

private typealias SdkHttpErrorFactory =
    (Int, String, ByteArray, Map<String, String>, String?) -> SdkHttpError

private val SDK_STATUS_ERRORS: Map<Int, SdkHttpErrorFactory> =
    mapOf(
        400 to ::SdkBadRequestError,
        401 to ::SdkUnauthorizedError,
        403 to ::SdkPermissionDeniedError,
        404 to ::SdkNotFoundError,
        409 to ::SdkConflictError,
        422 to ::SdkUnprocessableEntityError,
        429 to ::SdkRateLimitError,
    )

private fun sdkHttpErrorMessage(
    statusCode: Int,
    statusText: String,
    body: ByteArray,
    headers: Map<String, String>,
): String {
    val status =
        if (statusText.isBlank()) "HTTP $statusCode" else "HTTP $statusCode ${statusText.trim()}"
    val detail = sdkHttpErrorDetail(body, headers)
    return if (detail == null) status else "$status: $detail"
}

private fun sdkHttpErrorDetail(body: ByteArray, headers: Map<String, String>): String? {
    val decoder = Charsets.UTF_8.newDecoder()
    val text = runCatching { decoder.decode(java.nio.ByteBuffer.wrap(body)).toString() }.getOrNull()
    if (text.isNullOrEmpty()) return null
    val parsed = runCatching { com.fasterxml.jackson.databind.ObjectMapper().readTree(text) }
    val node = parsed.getOrNull()
    val contentType = headers.entries.firstOrNull { it.key.equals("content-type", true) }?.value
    val mediaType = contentType?.substringBefore(';')?.trim()?.lowercase().orEmpty()
    val detail =
        when {
            node != null -> sdkJsonErrorDetail(node)
            mediaType.isEmpty() || mediaType.startsWith("text/") -> text
            else -> null
        }
    return detail?.let(::sdkNormalizeHttpErrorDetail)
}

private fun sdkJsonErrorDetail(root: com.fasterxml.jackson.databind.JsonNode): String? {
    if (!root.isObject) return null
    val error = root.get("error")
    val candidates =
        listOf(
            root.get("message"),
            root.get("detail"),
            error?.get("message"),
            error?.get("detail"),
            error,
        )
    return candidates.firstOrNull { it?.isTextual == true }?.textValue()
}

private fun sdkNormalizeHttpErrorDetail(value: String): String? {
    val normalized = value.trim().replace(Regex("\\s+"), " ")
    if (normalized.isEmpty() || normalized.any { it.isISOControl() && !it.isWhitespace() }) {
        return null
    }
    val points = normalized.codePoints().toArray()
    if (points.size <= SDK_HTTP_ERROR_DETAIL_LIMIT) return normalized
    return String(points, 0, SDK_HTTP_ERROR_DETAIL_LIMIT) + "…"
}

/** Thrown for connection / DNS / socket failures. */
class SdkNetworkError(
    cause: Throwable,
    override val requestId: String? = null,
) : SdkError(cause.message ?: cause::class.java.simpleName, cause)

/** Thrown when a request exceeds its configured timeout. */
class SdkTimeoutError(
    val elapsed: Duration,
    override val requestId: String? = null,
    cause: Throwable? = null,
) : SdkError("Request timed out after ${elapsed.toMillis()}ms", cause)

