// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk


class LocationNamespace(private val clientConfig: ClientConfig) {
    /**
     * Lists locations that can be visited within the games, including cities and routes within regions. Use `limit` and `offset` to control the result page, or `q` to filter locations by name with a case-insensitive query.
     *
     * Locations that can be visited within the games. Locations make up sizable portions of regions, like cities or routes.
     */
    fun list(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedLocationSummaryList {
        return sdk.methods.Location.locationList(clientConfig, limit, offset, q, options)
    }

    /**
     * Lists locations that can be visited within the games, including cities and routes within regions. Use `limit` and `offset` to control the result page, or `q` to filter locations by name with a case-insensitive query.
     *
     * Locations that can be visited within the games. Locations make up sizable portions of regions, like cities or routes.
     */
    fun listPaginated(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (LocationSummary) -> Boolean) {
        sdk.methods.Location.locationListPaginated(clientConfig, limit, offset, q, options, yieldFn)
    }

    /**
     * Retrieves a location, which represents a visitable area within a game, such as a city or route. Use the `id` path parameter to identify the location; the identifier can be a string or an integer.
     *
     * Locations that can be visited within the games. Locations make up sizable portions of regions, like cities or routes.
     */
    fun retrieve(id: String, options: RequestOptions? = null): LocationDetail {
        return sdk.methods.Location.locationRetrieve(clientConfig, id, options)
    }

    /**
     * Lists location areas, which represent sections of a location such as floors in a building or cave. Use `limit` to control the number of results and `offset` to choose the starting index; each area has its own possible Pokémon encounters.
     *
     * Location areas are sections of areas, such as floors in a building or cave. Each area has its own set of possible Pokémon encounters.
     */
    fun areaList(limit: Int? = null, offset: Int? = null, options: RequestOptions? = null): PaginatedLocationAreaSummaryList {
        return sdk.methods.Location.locationAreaList(clientConfig, limit, offset, options)
    }

    /**
     * Lists location areas, which represent sections of a location such as floors in a building or cave. Use `limit` to control the number of results and `offset` to choose the starting index; each area has its own possible Pokémon encounters.
     *
     * Location areas are sections of areas, such as floors in a building or cave. Each area has its own set of possible Pokémon encounters.
     */
    fun areaListPaginated(limit: Int? = null, offset: Int? = null, options: RequestOptions? = null, yieldFn: (LocationAreaSummary) -> Boolean) {
        sdk.methods.Location.locationAreaListPaginated(clientConfig, limit, offset, options, yieldFn)
    }

    /**
     * Retrieves a location area, which represents a section of a location such as a building floor or cave area. Use the `id` path parameter to identify the area and retrieve its encounter information, location, and game-specific details.
     *
     * Location areas are sections of areas, such as floors in a building or cave. Each area has its own set of possible Pokémon encounters.
     */
    fun areaRetrieve(id: Int, options: RequestOptions? = null): LocationAreaDetail {
        return sdk.methods.Location.locationAreaRetrieve(clientConfig, id, options)
    }

    /**
     * Lists Pal Park areas used to group Pokémon encounters. Use `limit` and `offset` to paginate the results, or use `q` to search area names when running the API locally.
     *
     * Areas used for grouping Pokémon encounters in Pal Park. They're like habitats that are specific to Pal Park.
     */
    fun palParkAreaList(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedPalParkAreaSummaryList {
        return sdk.methods.Location.palParkAreaList(clientConfig, limit, offset, q, options)
    }

    /**
     * Lists Pal Park areas used to group Pokémon encounters. Use `limit` and `offset` to paginate the results, or use `q` to search area names when running the API locally.
     *
     * Areas used for grouping Pokémon encounters in Pal Park. They're like habitats that are specific to Pal Park.
     */
    fun palParkAreaListPaginated(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (PalParkAreaSummary) -> Boolean) {
        sdk.methods.Location.palParkAreaListPaginated(clientConfig, limit, offset, q, options, yieldFn)
    }

    /**
     * Retrieves a Pal Park area and its associated Pokémon encounters. Use the area identifier to look up its localized names and the Pokémon species encountered there.
     *
     * Areas used for grouping Pokémon encounters in Pal Park. They're like habitats that are specific to Pal Park.
     */
    fun palParkAreaRetrieve(id: String, options: RequestOptions? = null): PalParkAreaDetail {
        return sdk.methods.Location.palParkAreaRetrieve(clientConfig, id, options)
    }

    /**
     * Lists regions, which are organized areas of the Pokémon world with distinct species that can be encountered. Use `limit` and `offset` to page through the available regions, or use `q` to filter them by name; `q` is available only on local installations.
     *
     * A region is an organized area of the Pokémon world. Most often, the main difference between regions is the species of Pokémon that can be encountered within them.
     */
    fun regionList(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedRegionSummaryList {
        return sdk.methods.Location.regionList(clientConfig, limit, offset, q, options)
    }

    /**
     * Lists regions, which are organized areas of the Pokémon world with distinct species that can be encountered. Use `limit` and `offset` to page through the available regions, or use `q` to filter them by name; `q` is available only on local installations.
     *
     * A region is an organized area of the Pokémon world. Most often, the main difference between regions is the species of Pokémon that can be encountered within them.
     */
    fun regionListPaginated(limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (RegionSummary) -> Boolean) {
        sdk.methods.Location.regionListPaginated(clientConfig, limit, offset, q, options, yieldFn)
    }

    /**
     * Retrieves a region record describing an organized area of the Pokémon world. Use the `id` path parameter to identify the region, and inspect its locations, main generation, Pokédexes, and version groups.
     *
     * A region is an organized area of the Pokémon world. Most often, the main difference between regions is the species of Pokémon that can be encountered within them.
     */
    fun regionRetrieve(id: String, options: RequestOptions? = null): RegionDetail {
        return sdk.methods.Location.regionRetrieve(clientConfig, id, options)
    }

}
