// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

class MachinesNamespace(private val clientConfig: ClientConfig) {
    /**
     * Lists machines, which represent items that teach moves to Pokémon. Use `limit` and `offset`
     * to control the results page; `q` filters names case-insensitively and is available only in
     * local deployments.
     *
     * Machines are the representation of items that teach moves to Pokémon. They vary from version
     * to version, so it is not certain that one specific TM or HM corresponds to a single Machine.
     */
    fun list(
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
    ): PaginatedMachineSummaryList {
        return sdk.methods.Machines.machineList(clientConfig, limit, offset, q, options)
    }

    /**
     * Lists machines, which represent items that teach moves to Pokémon. Use `limit` and `offset`
     * to control the results page; `q` filters names case-insensitively and is available only in
     * local deployments.
     *
     * Machines are the representation of items that teach moves to Pokémon. They vary from version
     * to version, so it is not certain that one specific TM or HM corresponds to a single Machine.
     */
    fun listPaginated(
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
        yieldFn: (MachineSummary) -> Boolean,
    ) {
        sdk.methods.Machines.machineListPaginated(clientConfig, limit, offset, q, options, yieldFn)
    }

    /**
     * Retrieves a machine, which represents an item that teaches a move to a Pokémon. Use the `id`
     * path parameter to identify the machine and retrieve its item, move, and version group.
     *
     * Machines are the representation of items that teach moves to Pokémon. They vary from version
     * to version, so it is not certain that one specific TM or HM corresponds to a single Machine.
     */
    fun retrieve(id: String, options: RequestOptions? = null): MachineDetail {
        return sdk.methods.Machines.machineRetrieve(clientConfig, id, options)
    }
}
