// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

typealias PokemonEncounterResponse = sdk.models.PokemonEncounterResponse

typealias PokemonEncounterVersionDetailResponse = sdk.models.PokemonEncounterVersionDetailResponse

typealias PokemonEvolution = sdk.models.PokemonEvolution

typealias PokemonFormDetail = sdk.models.PokemonFormDetail

typealias PokemonFormFlavorText = sdk.models.PokemonFormFlavorText

typealias PokemonFormName = sdk.models.PokemonFormName

typealias PokemonFormSprites = sdk.models.PokemonFormSprites

typealias PokemonFormSummary = sdk.models.PokemonFormSummary

typealias PokemonFormTriggerCondition = sdk.models.PokemonFormTriggerCondition

typealias PokemonFormType = sdk.models.PokemonFormType

typealias PokemonGameIndex = sdk.models.PokemonGameIndex

typealias PokemonHabitatDetail = sdk.models.PokemonHabitatDetail

typealias PokemonHabitatName = sdk.models.PokemonHabitatName

typealias PokemonHabitatSummary = sdk.models.PokemonHabitatSummary

typealias PokemonHeldItem = sdk.models.PokemonHeldItem

typealias PokemonHeldItemVersion = sdk.models.PokemonHeldItemVersion

typealias PokemonMove = sdk.models.PokemonMove

typealias PokemonMoveVersionGroup = sdk.models.PokemonMoveVersionGroup

typealias PokemonPastAbility = sdk.models.PokemonPastAbility

typealias PokemonPastStat = sdk.models.PokemonPastStat

typealias PokemonPastType = sdk.models.PokemonPastType

typealias PokemonShapeAwesomeName = sdk.models.PokemonShapeAwesomeName

typealias PokemonShapeDetail = sdk.models.PokemonShapeDetail

typealias PokemonShapeName = sdk.models.PokemonShapeName

typealias PokemonShapeSummary = sdk.models.PokemonShapeSummary

typealias PokemonSpeciesDescription = sdk.models.PokemonSpeciesDescription

typealias PokemonSpeciesDetail = sdk.models.PokemonSpeciesDetail

typealias PokemonSpeciesFlavorText = sdk.models.PokemonSpeciesFlavorText

typealias PokemonSpeciesGenus = sdk.models.PokemonSpeciesGenus

typealias PokemonSpeciesName = sdk.models.PokemonSpeciesName

typealias PokemonSpeciesPalParkEncounter = sdk.models.PokemonSpeciesPalParkEncounter

typealias PokemonSpeciesSummary = sdk.models.PokemonSpeciesSummary

typealias PokemonSpeciesVariety = sdk.models.PokemonSpeciesVariety

typealias PokemonSprites = sdk.models.PokemonSprites

typealias PokemonStat = sdk.models.PokemonStat

typealias PokemonSummary = sdk.models.PokemonSummary

typealias PokemonType = sdk.models.PokemonType

typealias RegionDetail = sdk.models.RegionDetail

typealias RegionName = sdk.models.RegionName

typealias RegionSummary = sdk.models.RegionSummary

typealias StatAffectingMoves = sdk.models.StatAffectingMoves

typealias StatAffectingNatures = sdk.models.StatAffectingNatures

typealias StatDetail = sdk.models.StatDetail

typealias StatName = sdk.models.StatName

typealias StatSummary = sdk.models.StatSummary

typealias SuperContestEffectDetail = sdk.models.SuperContestEffectDetail

typealias SuperContestEffectFlavorText = sdk.models.SuperContestEffectFlavorText

typealias SuperContestEffectSummary = sdk.models.SuperContestEffectSummary

typealias TypeDetail = sdk.models.TypeDetail

typealias TypeGameIndex = sdk.models.TypeGameIndex

typealias TypeName = sdk.models.TypeName

typealias TypePastRelationships = sdk.models.TypePastRelationships

typealias TypePokemon = sdk.models.TypePokemon

typealias TypeRelationships = sdk.models.TypeRelationships

typealias TypeSprite = sdk.models.TypeSprite

typealias TypeSummary = sdk.models.TypeSummary

typealias VersionDetail = sdk.models.VersionDetail

typealias VersionGroupDetail = sdk.models.VersionGroupDetail

typealias VersionGroupSummary = sdk.models.VersionGroupSummary

typealias VersionName = sdk.models.VersionName

typealias VersionSummary = sdk.models.VersionSummary
