// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

/**
 * Canonical validation helpers. Each throws [SdkValidationError] on failure.
 */
object Validation {

    fun validatePattern(field: String, value: String, pattern: String) {
        if (!Regex(pattern).containsMatchIn(value)) {
            throw SdkValidationError(field, "pattern",
                "Validation failed for '$field': must match pattern $pattern")
        }
    }

}
