// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

plugins {
    kotlin("jvm") version "2.4.10"
    `maven-publish`
    id("dev.detekt") version "2.0.0-alpha.5"
}

group = "dev.octri.demo"
version = "2.10.1"
description = "Unofficial PokéAPI demo SDK generated by Octri from PokéAPI's public OpenAPI specification."

repositories {
    mavenCentral()
}

val ktfmt by configurations.creating

dependencies {
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.15.2")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.2")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.4.10")
    ktfmt("com.facebook:ktfmt:0.64")
    testImplementation("org.jetbrains.kotlin:kotlin-test:2.4.10")
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.4")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.11.4")
}

// Official ktfmt CLI JAR. Java bytecode keeps this formatter portable across
// Linux arm64 and x64 runners; benchmark checks run Gradle offline after this
// configuration is resolved by prepareKtfmt.
tasks.register<Copy>("prepareKtfmt") {
    from(ktfmt)
    into(layout.buildDirectory.dir("tooling/ktfmt"))
}

fun JavaExec.runKtfmt(vararg arguments: String) {
    classpath = ktfmt
    maxHeapSize = "384m"
    jvmArgs("-XX:ActiveProcessorCount=2")
    mainClass.set("com.facebook.ktfmt.cli.Main")
    args(*arguments)
}

// ktfmt can wrap an outer expression and leave an inner one for the next pass,
// so formatting runs it twice to reach the output ktfmtCheck accepts.
val ktfmtFirstPass = tasks.register<JavaExec>("ktfmtFirstPass") {
    runKtfmt("--kotlinlang-style", "--quiet", "src")
}

tasks.register<JavaExec>("ktfmtFormat") {
    group = "formatting"
    description = "Formats generated Kotlin sources with ktfmt."
    dependsOn(ktfmtFirstPass)
    runKtfmt("--kotlinlang-style", "--quiet", "src")
}

tasks.register<JavaExec>("ktfmtCheck") {
    group = "verification"
    description = "Checks generated Kotlin sources with ktfmt."
    runKtfmt(
        "--kotlinlang-style",
        "--dry-run",
        "--set-exit-if-changed",
        "--quiet",
        "src",
    )
}

kotlin {
    jvmToolchain(21)
    compilerOptions {
        allWarningsAsErrors.set(true)
        freeCompilerArgs.add("-Xmetadata-version=1.9.0")
    }
}

// Copies all runtime JARs into build/dependency/ for use by external tooling
// (e.g. the kotlinc + java integration test runner).
tasks.register<Copy>("copyDeps") {
    from(configurations.runtimeClasspath)
    into(layout.buildDirectory.dir("dependency"))
}

tasks.test {
    useJUnitPlatform()
    // The method tests run only against the mock server this names, so a result
    // cached without it must not stand in for a run with it.
    inputs.property(
        "sdkMethodTestBaseUrl",
        providers.environmentVariable("SDK_METHOD_TEST_BASE_URL").orElse(""),
    )
    // The suites read their cases from test/ at run time, so an edited fixture
    // must invalidate a cached result.
    inputs.files(fileTree("test"))
        .withPropertyName("sdkTestFixtures")
        .withPathSensitivity(PathSensitivity.RELATIVE)
}

detekt {
    buildUponDefaultConfig = true
    allRules = false
    config.setFrom(files("detekt.yml"))
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            artifactId = "pokeapiUnofficialSdk"
            pom {
                name.set("PokéAPI Unofficial Demo SDK")
                description.set(project.description)
                url.set("https://octri-8tky5bfpaxae.octri.dev/")
                properties.put("keywords", "pokeapi,octri,sdk,unofficial,demo")
                licenses {
                    license {
                        name.set("MIT License")
                        url.set("https://opensource.org/license/mit")
                    }
                }
                scm {
                    connection.set("scm:git:https://github.com/octri-dev/pokeapi-kotlin-unofficial-demo-sdk.git")
                    developerConnection.set("scm:git:ssh://git@github.com/octri-dev/pokeapi-kotlin-unofficial-demo-sdk.git")
                    url.set("https://github.com/octri-dev/pokeapi-kotlin-unofficial-demo-sdk")
                }
            }
        }
    }
}
