// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dev.octri.demo.pokeapiUnofficialSdk.methods

import dev.octri.demo.pokeapiUnofficialSdk.BerryDetail
import dev.octri.demo.pokeapiUnofficialSdk.BerryFirmnessDetail
import dev.octri.demo.pokeapiUnofficialSdk.BerryFirmnessSummary
import dev.octri.demo.pokeapiUnofficialSdk.BerryFlavorDetail
import dev.octri.demo.pokeapiUnofficialSdk.BerryFlavorSummary
import dev.octri.demo.pokeapiUnofficialSdk.BerrySummary
import dev.octri.demo.pokeapiUnofficialSdk.ClientConfig
import dev.octri.demo.pokeapiUnofficialSdk.PaginatedBerryFirmnessSummaryList
import dev.octri.demo.pokeapiUnofficialSdk.PaginatedBerryFlavorSummaryList
import dev.octri.demo.pokeapiUnofficialSdk.PaginatedBerrySummaryList
import dev.octri.demo.pokeapiUnofficialSdk.RequestOptions
import dev.octri.demo.pokeapiUnofficialSdk.SdkClient

object Berries {

    /**
     * Lists berries, which Pokémon can eat to restore HP or status conditions, enhance stats, or
     * negate damage. Use `limit` and `offset` to select a result window, and `q` to filter by berry
     * name on a local API instance.
     *
     * Berries are small fruits that can provide HP and status condition restoration, stat
     * enhancement, and even damage negation when eaten by Pokémon. Check out Bulbapedia for greater
     * detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query applied on the
     *   `name` property.
     */
    fun berryList(
        clientConfig: ClientConfig,
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
    ): PaginatedBerrySummaryList {
        return SdkClient.request<PaginatedBerrySummaryList>(
                SdkClient.RequestSpec(
                    "GET",
                    "/api/v2/berry/",
                    config = clientConfig,
                    query =
                        mapOf(
                            "limit" to SdkClient.queryValue(limit, "form", true),
                            "offset" to SdkClient.queryValue(offset, "form", true),
                            "q" to SdkClient.queryValue(q, "form", true),
                        ),
                    operationId = "berryList",
                    decoder = SdkClient.ResponseDecoder.JSON,
                    options = options,
                )
            )
            .data
    }

    /**
     * Lists berries, which Pokémon can eat to restore HP or status conditions, enhance stats, or
     * negate damage. Use `limit` and `offset` to select a result window, and `q` to filter by berry
     * name on a local API instance.
     *
     * Berries are small fruits that can provide HP and status condition restoration, stat
     * enhancement, and even damage negation when eaten by Pokémon. Check out Bulbapedia for greater
     * detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query applied on the
     *   `name` property.
     */
    fun berryListPaginated(
        clientConfig: ClientConfig,
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
        yieldFn: (BerrySummary) -> Boolean,
    ) {
        var page: PaginatedBerrySummaryList = berryList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page =
                SdkClient.request<PaginatedBerrySummaryList>(
                        SdkClient.RequestSpec(
                            method = "GET",
                            path = nextUrl,
                            operationId = "berryList",
                            config = clientConfig,
                            options = options,
                        )
                    )
                    .data
        }
    }

    data class BerryListPage(
        val data: PaginatedBerrySummaryList,
        val items: List<BerrySummary>,
        val hasMore: Boolean,
    )

    fun berryListPages(
        clientConfig: ClientConfig,
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
        yieldPage: (BerryListPage) -> Boolean,
    ) {
        var page: PaginatedBerrySummaryList = berryList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(BerryListPage(page, items, hasMore))) return
            if (!hasMore) return
            page =
                SdkClient.request<PaginatedBerrySummaryList>(
                        SdkClient.RequestSpec(
                            method = "GET",
                            path = nextUrl,
                            operationId = "berryList",
                            config = clientConfig,
                            options = options,
                        )
                    )
                    .data
        }
    }

    /**
     * Retrieves a berry and its growing properties, firmness, flavors, associated item, and natural
     * gift data. Supply the berry's `id` as a string or integer to look up the record.
     *
     * Berries are small fruits that can provide HP and status condition restoration, stat
     * enhancement, and even damage negation when eaten by Pokémon. Check out Bulbapedia for greater
     * detail.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun berryRetrieve(
        clientConfig: ClientConfig,
        id: String,
        options: RequestOptions? = null,
    ): BerryDetail {
        return SdkClient.request<BerryDetail>(
                SdkClient.RequestSpec(
                    "GET",
                    "/api/v2/berry/${SdkClient.encodePathSegment(id)}/",
                    config = clientConfig,
                    operationId = "berryRetrieve",
                    decoder = SdkClient.ResponseDecoder.JSON,
                    options = options,
                )
            )
            .data
    }

    /**
     * Lists berry firmness categories, which describe how soft or hard berries are. Use `limit` and
     * `offset` to select a result window, and `q` to filter categories by name on a local API
     * instance.
     *
     * Berries can be soft or hard. Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query applied on the
     *   `name` property.
     */
    fun berryFirmnessList(
        clientConfig: ClientConfig,
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
    ): PaginatedBerryFirmnessSummaryList {
        return SdkClient.request<PaginatedBerryFirmnessSummaryList>(
                SdkClient.RequestSpec(
                    "GET",
                    "/api/v2/berry-firmness/",
                    config = clientConfig,
                    query =
                        mapOf(
                            "limit" to SdkClient.queryValue(limit, "form", true),
                            "offset" to SdkClient.queryValue(offset, "form", true),
                            "q" to SdkClient.queryValue(q, "form", true),
                        ),
                    operationId = "berryFirmnessList",
                    decoder = SdkClient.ResponseDecoder.JSON,
                    options = options,
                )
            )
            .data
    }

    /**
     * Lists berry firmness categories, which describe how soft or hard berries are. Use `limit` and
     * `offset` to select a result window, and `q` to filter categories by name on a local API
     * instance.
     *
     * Berries can be soft or hard. Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query applied on the
     *   `name` property.
     */
    fun berryFirmnessListPaginated(
        clientConfig: ClientConfig,
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
        yieldFn: (BerryFirmnessSummary) -> Boolean,
    ) {
        var page: PaginatedBerryFirmnessSummaryList =
            berryFirmnessList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page =
                SdkClient.request<PaginatedBerryFirmnessSummaryList>(
                        SdkClient.RequestSpec(
                            method = "GET",
                            path = nextUrl,
                            operationId = "berryFirmnessList",
                            config = clientConfig,
                            options = options,
                        )
                    )
                    .data
        }
    }

    data class BerryFirmnessListPage(
        val data: PaginatedBerryFirmnessSummaryList,
        val items: List<BerryFirmnessSummary>,
        val hasMore: Boolean,
    )

    fun berryFirmnessListPages(
        clientConfig: ClientConfig,
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
        yieldPage: (BerryFirmnessListPage) -> Boolean,
    ) {
        var page: PaginatedBerryFirmnessSummaryList =
            berryFirmnessList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(BerryFirmnessListPage(page, items, hasMore))) return
            if (!hasMore) return
            page =
                SdkClient.request<PaginatedBerryFirmnessSummaryList>(
                        SdkClient.RequestSpec(
                            method = "GET",
                            path = nextUrl,
                            operationId = "berryFirmnessList",
                            config = clientConfig,
                            options = options,
                        )
                    )
                    .data
        }
    }

    /**
     * Retrieves a berry firmness category and the berries assigned to it. Supply the category's
     * `id` as a string or integer to look up its associated berry list and localized names.
     *
     * Berries can be soft or hard. Check out Bulbapedia for greater detail.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun berryFirmnessRetrieve(
        clientConfig: ClientConfig,
        id: String,
        options: RequestOptions? = null,
    ): BerryFirmnessDetail {
        return SdkClient.request<BerryFirmnessDetail>(
                SdkClient.RequestSpec(
                    "GET",
                    "/api/v2/berry-firmness/${SdkClient.encodePathSegment(id)}/",
                    config = clientConfig,
                    operationId = "berryFirmnessRetrieve",
                    decoder = SdkClient.ResponseDecoder.JSON,
                    options = options,
                )
            )
            .data
    }

    /**
     * Lists berry flavors, which determine whether a Pokémon benefits or suffers from eating a
     * berry based on its nature. Use `limit` and `offset` to select a result window, and `q` to
     * filter flavors by name on a local API instance.
     *
     * Flavors determine whether a Pokémon will benefit or suffer from eating a berry based on their
     * **nature**. Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query applied on the
     *   `name` property.
     */
    fun berryFlavorList(
        clientConfig: ClientConfig,
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
    ): PaginatedBerryFlavorSummaryList {
        return SdkClient.request<PaginatedBerryFlavorSummaryList>(
                SdkClient.RequestSpec(
                    "GET",
                    "/api/v2/berry-flavor/",
                    config = clientConfig,
                    query =
                        mapOf(
                            "limit" to SdkClient.queryValue(limit, "form", true),
                            "offset" to SdkClient.queryValue(offset, "form", true),
                            "q" to SdkClient.queryValue(q, "form", true),
                        ),
                    operationId = "berryFlavorList",
                    decoder = SdkClient.ResponseDecoder.JSON,
                    options = options,
                )
            )
            .data
    }

    /**
     * Lists berry flavors, which determine whether a Pokémon benefits or suffers from eating a
     * berry based on its nature. Use `limit` and `offset` to select a result window, and `q` to
     * filter flavors by name on a local API instance.
     *
     * Flavors determine whether a Pokémon will benefit or suffer from eating a berry based on their
     * **nature**. Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query applied on the
     *   `name` property.
     */
    fun berryFlavorListPaginated(
        clientConfig: ClientConfig,
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
        yieldFn: (BerryFlavorSummary) -> Boolean,
    ) {
        var page: PaginatedBerryFlavorSummaryList =
            berryFlavorList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page =
                SdkClient.request<PaginatedBerryFlavorSummaryList>(
                        SdkClient.RequestSpec(
                            method = "GET",
                            path = nextUrl,
                            operationId = "berryFlavorList",
                            config = clientConfig,
                            options = options,
                        )
                    )
                    .data
        }
    }

    data class BerryFlavorListPage(
        val data: PaginatedBerryFlavorSummaryList,
        val items: List<BerryFlavorSummary>,
        val hasMore: Boolean,
    )

    fun berryFlavorListPages(
        clientConfig: ClientConfig,
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
        yieldPage: (BerryFlavorListPage) -> Boolean,
    ) {
        var page: PaginatedBerryFlavorSummaryList =
            berryFlavorList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(BerryFlavorListPage(page, items, hasMore))) return
            if (!hasMore) return
            page =
                SdkClient.request<PaginatedBerryFlavorSummaryList>(
                        SdkClient.RequestSpec(
                            method = "GET",
                            path = nextUrl,
                            operationId = "berryFlavorList",
                            config = clientConfig,
                            options = options,
                        )
                    )
                    .data
        }
    }

    /**
     * Retrieves a berry flavor and the berries associated with it, including their flavor potency.
     * Supply the flavor's `id` as a string or integer to look up its contest type and localized
     * names.
     *
     * Flavors determine whether a Pokémon will benefit or suffer from eating a berry based on their
     * **nature**. Check out Bulbapedia for greater detail.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun berryFlavorRetrieve(
        clientConfig: ClientConfig,
        id: String,
        options: RequestOptions? = null,
    ): BerryFlavorDetail {
        return SdkClient.request<BerryFlavorDetail>(
                SdkClient.RequestSpec(
                    "GET",
                    "/api/v2/berry-flavor/${SdkClient.encodePathSegment(id)}/",
                    config = clientConfig,
                    operationId = "berryFlavorRetrieve",
                    decoder = SdkClient.ResponseDecoder.JSON,
                    options = options,
                )
            )
            .data
    }
}
