// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dev.octri.demo.pokeapiUnofficialSdk.methods

import dev.octri.demo.pokeapiUnofficialSdk.ClientConfig
import dev.octri.demo.pokeapiUnofficialSdk.GenerationDetail
import dev.octri.demo.pokeapiUnofficialSdk.GenerationSummary
import dev.octri.demo.pokeapiUnofficialSdk.PaginatedGenerationSummaryList
import dev.octri.demo.pokeapiUnofficialSdk.PaginatedPokedexSummaryList
import dev.octri.demo.pokeapiUnofficialSdk.PaginatedVersionGroupSummaryList
import dev.octri.demo.pokeapiUnofficialSdk.PaginatedVersionSummaryList
import dev.octri.demo.pokeapiUnofficialSdk.PokedexDetail
import dev.octri.demo.pokeapiUnofficialSdk.PokedexSummary
import dev.octri.demo.pokeapiUnofficialSdk.RequestOptions
import dev.octri.demo.pokeapiUnofficialSdk.SdkClient
import dev.octri.demo.pokeapiUnofficialSdk.VersionDetail
import dev.octri.demo.pokeapiUnofficialSdk.VersionGroupDetail
import dev.octri.demo.pokeapiUnofficialSdk.VersionGroupSummary
import dev.octri.demo.pokeapiUnofficialSdk.VersionSummary

object Games {


    /**
     * Lists generations, which group Pokémon games by the Pokémon, moves, abilities, and types they include. Use `limit` and `offset` to control the result page, or search generation names with `q`, which is available only on local deployments.
     *
     * A generation is a grouping of the Pokémon games that separates them based on the Pokémon they include. In each generation, a new set of Pokémon, Moves, Abilities and Types that did not exist in the previous generation are released.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun generationList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedGenerationSummaryList {
        return SdkClient.request<PaginatedGenerationSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/generation/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "generationList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists generations, which group Pokémon games by the Pokémon, moves, abilities, and types they include. Use `limit` and `offset` to control the result page, or search generation names with `q`, which is available only on local deployments.
     *
     * A generation is a grouping of the Pokémon games that separates them based on the Pokémon they include. In each generation, a new set of Pokémon, Moves, Abilities and Types that did not exist in the previous generation are released.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun generationListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (GenerationSummary) -> Boolean) {
        var page: PaginatedGenerationSummaryList = generationList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedGenerationSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "generationList", config = clientConfig, options = options)).data
        }
    }

    data class GenerationListPage(
        val data: PaginatedGenerationSummaryList,
        val items: List<GenerationSummary>,
        val hasMore: Boolean,
    )

    fun generationListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (GenerationListPage) -> Boolean) {
        var page: PaginatedGenerationSummaryList = generationList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(GenerationListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedGenerationSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "generationList", config = clientConfig, options = options)).data
        }
    }



    /**
     * Retrieves a generation and its associated Pokémon data. Use the `id` path parameter to select a generation and view its region, Pokémon species, moves, abilities, types, and version groups.
     *
     * A generation is a grouping of the Pokémon games that separates them based on the Pokémon they include. In each generation, a new set of Pokémon, Moves, Abilities and Types that did not exist in the previous generation are released.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun generationRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): GenerationDetail {
        return SdkClient.request<GenerationDetail>(SdkClient.RequestSpec("GET", "/api/v2/generation/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "generationRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }







    /**
     * Lists Pokédex records that catalog Pokémon entries for regions or other defined groups. Use `limit` and `offset` to paginate the results, or use `q` to search Pokédex names when running the API locally.
     *
     * A Pokédex is a handheld electronic encyclopedia device; one which is capable of recording and retaining information of the various Pokémon in a given region with the exception of the national dex and some smaller dexes related to portions of a region. See Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun pokedexList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedPokedexSummaryList {
        return SdkClient.request<PaginatedPokedexSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/pokedex/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "pokedexList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists Pokédex records that catalog Pokémon entries for regions or other defined groups. Use `limit` and `offset` to paginate the results, or use `q` to search Pokédex names when running the API locally.
     *
     * A Pokédex is a handheld electronic encyclopedia device; one which is capable of recording and retaining information of the various Pokémon in a given region with the exception of the national dex and some smaller dexes related to portions of a region. See Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun pokedexListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (PokedexSummary) -> Boolean) {
        var page: PaginatedPokedexSummaryList = pokedexList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedPokedexSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "pokedexList", config = clientConfig, options = options)).data
        }
    }

    data class PokedexListPage(
        val data: PaginatedPokedexSummaryList,
        val items: List<PokedexSummary>,
        val hasMore: Boolean,
    )

    fun pokedexListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (PokedexListPage) -> Boolean) {
        var page: PaginatedPokedexSummaryList = pokedexList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(PokedexListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedPokedexSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "pokedexList", config = clientConfig, options = options)).data
        }
    }



    /**
     * Retrieves a Pokédex record and its catalog of Pokémon species. Use the Pokédex identifier to look up its region, version groups, and numbered Pokémon entries.
     *
     * A Pokédex is a handheld electronic encyclopedia device; one which is capable of recording and retaining information of the various Pokémon in a given region with the exception of the national dex and some smaller dexes related to portions of a region. See Bulbapedia for greater detail.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun pokedexRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): PokedexDetail {
        return SdkClient.request<PokedexDetail>(SdkClient.RequestSpec("GET", "/api/v2/pokedex/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "pokedexRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }







    /**
     * Lists game versions such as Red, Blue, and Yellow. Use `limit` and `offset` to control the results, or use `q` to search version names case-insensitively; `q` is available only on the local API.
     *
     * Versions of the games, e.g., Red, Blue or Yellow.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun versionList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedVersionSummaryList {
        return SdkClient.request<PaginatedVersionSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/version/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "versionList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists game versions such as Red, Blue, and Yellow. Use `limit` and `offset` to control the results, or use `q` to search version names case-insensitively; `q` is available only on the local API.
     *
     * Versions of the games, e.g., Red, Blue or Yellow.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun versionListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (VersionSummary) -> Boolean) {
        var page: PaginatedVersionSummaryList = versionList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedVersionSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "versionList", config = clientConfig, options = options)).data
        }
    }

    data class VersionListPage(
        val data: PaginatedVersionSummaryList,
        val items: List<VersionSummary>,
        val hasMore: Boolean,
    )

    fun versionListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (VersionListPage) -> Boolean) {
        var page: PaginatedVersionSummaryList = versionList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(VersionListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedVersionSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "versionList", config = clientConfig, options = options)).data
        }
    }



    /**
     * Retrieves a game version, such as Red, Blue, or Yellow. Use the `id` path parameter to identify the version, then inspect its localized names and associated version group.
     *
     * Versions of the games, e.g., Red, Blue or Yellow.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun versionRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): VersionDetail {
        return SdkClient.request<VersionDetail>(SdkClient.RequestSpec("GET", "/api/v2/version/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "versionRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }







    /**
     * Lists version groups that categorize highly similar game versions. Use `limit` and `offset` to control the results, or use `q` to search version group names case-insensitively; `q` is available only on the local API.
     *
     * Version groups categorize highly similar versions of the games.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun versionGroupList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedVersionGroupSummaryList {
        return SdkClient.request<PaginatedVersionGroupSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/version-group/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "versionGroupList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists version groups that categorize highly similar game versions. Use `limit` and `offset` to control the results, or use `q` to search version group names case-insensitively; `q` is available only on the local API.
     *
     * Version groups categorize highly similar versions of the games.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun versionGroupListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (VersionGroupSummary) -> Boolean) {
        var page: PaginatedVersionGroupSummaryList = versionGroupList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedVersionGroupSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "versionGroupList", config = clientConfig, options = options)).data
        }
    }

    data class VersionGroupListPage(
        val data: PaginatedVersionGroupSummaryList,
        val items: List<VersionGroupSummary>,
        val hasMore: Boolean,
    )

    fun versionGroupListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (VersionGroupListPage) -> Boolean) {
        var page: PaginatedVersionGroupSummaryList = versionGroupList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(VersionGroupListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedVersionGroupSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "versionGroupList", config = clientConfig, options = options)).data
        }
    }



    /**
     * Retrieves a version group by its identifier. Version groups categorize highly similar game versions, and the response includes the associated generation, move-learn methods, Pokédexes, regions, and versions.
     *
     * Version groups categorize highly similar versions of the games.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun versionGroupRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): VersionGroupDetail {
        return SdkClient.request<VersionGroupDetail>(SdkClient.RequestSpec("GET", "/api/v2/version-group/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "versionGroupRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }







}
