// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dev.octri.demo.pokeapiUnofficialSdk.methods

import dev.octri.demo.pokeapiUnofficialSdk.ClientConfig
import dev.octri.demo.pokeapiUnofficialSdk.LanguageDetail
import dev.octri.demo.pokeapiUnofficialSdk.LanguageSummary
import dev.octri.demo.pokeapiUnofficialSdk.PaginatedLanguageSummaryList
import dev.octri.demo.pokeapiUnofficialSdk.PokeapiMetaResponse
import dev.octri.demo.pokeapiUnofficialSdk.RequestOptions
import dev.octri.demo.pokeapiUnofficialSdk.SdkClient

object Utility {

    /**
     * Returns metadata about the currently deployed API version. Use the `deploy_date`, `hash`, and
     * `tag` fields to identify the deployment; each value can be null.
     *
     * Returns metadata about the current deployed version of the API, including the git commit
     * hash, deploy date, and tag (if any).
     */
    fun metaRetrieve(
        clientConfig: ClientConfig,
        options: RequestOptions? = null,
    ): PokeapiMetaResponse {
        return SdkClient.request<PokeapiMetaResponse>(
                SdkClient.RequestSpec(
                    "GET",
                    "/api/v2/meta/",
                    config = clientConfig,
                    operationId = "metaRetrieve",
                    decoder = SdkClient.ResponseDecoder.JSON,
                    options = options,
                )
            )
            .data
    }

    /**
     * Lists languages used for translations of API resource information. Use `limit` and `offset`
     * to control the result page, or `q` to filter languages by name with a case-insensitive query.
     *
     * Languages for translations of API resource information.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query applied on the
     *   `name` property.
     */
    fun languageList(
        clientConfig: ClientConfig,
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
    ): PaginatedLanguageSummaryList {
        return SdkClient.request<PaginatedLanguageSummaryList>(
                SdkClient.RequestSpec(
                    "GET",
                    "/api/v2/language/",
                    config = clientConfig,
                    query =
                        mapOf(
                            "limit" to SdkClient.queryValue(limit, "form", true),
                            "offset" to SdkClient.queryValue(offset, "form", true),
                            "q" to SdkClient.queryValue(q, "form", true),
                        ),
                    operationId = "languageList",
                    decoder = SdkClient.ResponseDecoder.JSON,
                    options = options,
                )
            )
            .data
    }

    /**
     * Lists languages used for translations of API resource information. Use `limit` and `offset`
     * to control the result page, or `q` to filter languages by name with a case-insensitive query.
     *
     * Languages for translations of API resource information.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query applied on the
     *   `name` property.
     */
    fun languageListPaginated(
        clientConfig: ClientConfig,
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
        yieldFn: (LanguageSummary) -> Boolean,
    ) {
        var page: PaginatedLanguageSummaryList =
            languageList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page =
                SdkClient.request<PaginatedLanguageSummaryList>(
                        SdkClient.RequestSpec(
                            method = "GET",
                            path = nextUrl,
                            operationId = "languageList",
                            config = clientConfig,
                            options = options,
                        )
                    )
                    .data
        }
    }

    data class LanguageListPage(
        val data: PaginatedLanguageSummaryList,
        val items: List<LanguageSummary>,
        val hasMore: Boolean,
    )

    fun languageListPages(
        clientConfig: ClientConfig,
        limit: Int? = null,
        offset: Int? = null,
        q: String? = null,
        options: RequestOptions? = null,
        yieldPage: (LanguageListPage) -> Boolean,
    ) {
        var page: PaginatedLanguageSummaryList =
            languageList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(LanguageListPage(page, items, hasMore))) return
            if (!hasMore) return
            page =
                SdkClient.request<PaginatedLanguageSummaryList>(
                        SdkClient.RequestSpec(
                            method = "GET",
                            path = nextUrl,
                            operationId = "languageList",
                            config = clientConfig,
                            options = options,
                        )
                    )
                    .data
        }
    }

    /**
     * Retrieves a single language used for translations of API resource information. Use `id` to
     * identify the language whose official status, ISO codes, and localized names you want to
     * inspect.
     *
     * Languages for translations of API resource information.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun languageRetrieve(
        clientConfig: ClientConfig,
        id: String,
        options: RequestOptions? = null,
    ): LanguageDetail {
        return SdkClient.request<LanguageDetail>(
                SdkClient.RequestSpec(
                    "GET",
                    "/api/v2/language/${SdkClient.encodePathSegment(id)}/",
                    config = clientConfig,
                    operationId = "languageRetrieve",
                    decoder = SdkClient.ResponseDecoder.JSON,
                    options = options,
                )
            )
            .data
    }
}
