// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk.models

/** Typed representation of the `GenerationDetail` API schema. */
data class GenerationDetail(
    /** Required `integer` value serialized in the `id` wire field. */
    val id: Int,
    /** Required `string` value serialized in the `name` wire field. */
    val name: String,
    /** Required array value serialized in the `abilities` wire field. */
    val abilities: List<AbilitySummary>,
    /** Required object value serialized in the `main_region` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("main_region") val mainRegion: RegionSummary,
    /** Required array value serialized in the `moves` wire field. */
    val moves: List<MoveSummary>,
    /** Required array value serialized in the `names` wire field. */
    val names: List<GenerationName>,
    /** Required array value serialized in the `pokemon_species` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("pokemon_species")
    val pokemonSpecies: List<PokemonSpeciesSummary>,
    /** Required array value serialized in the `types` wire field. */
    val types: List<TypeSummary>,
    /** Required array value serialized in the `version_groups` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("version_groups")
    val versionGroups: List<VersionGroupSummary>,
)

/** Typed representation of the `GenerationName` API schema. */
data class GenerationName(
    /** Required `string` value serialized in the `name` wire field. */
    val name: String,
    /** Required object value serialized in the `language` wire field. */
    val language: LanguageSummary,
)

/** Typed representation of the `PaginatedGenerationSummaryList` API schema. */
data class PaginatedGenerationSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<GenerationSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedPokedexSummaryList` API schema. */
data class PaginatedPokedexSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<PokedexSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedVersionGroupSummaryList` API schema. */
data class PaginatedVersionGroupSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<VersionGroupSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedVersionSummaryList` API schema. */
data class PaginatedVersionSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<VersionSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PokedexDescription` API schema. */
data class PokedexDescription(
    /** Required object value serialized in the `language` wire field. */
    val language: LanguageSummary,
    /** Optional `string` value serialized in the `description` wire field. */
    val description: String? = null,
)

/** Typed representation of the `PokedexDetail` API schema. */
data class PokedexDetail(
    /** Required `integer` value serialized in the `id` wire field. */
    val id: Int,
    /** Required `string` value serialized in the `name` wire field. */
    val name: String,
    /** Required array value serialized in the `descriptions` wire field. */
    val descriptions: List<PokedexDescription>,
    /** Required array value serialized in the `names` wire field. */
    val names: List<PokedexName>,
    /** Required array value serialized in the `pokemon_entries` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("pokemon_entries")
    val pokemonEntries: List<PokemonDexNumber>,
    /** Required object value serialized in the `region` wire field. */
    val region: RegionSummary,
    /** Required array value serialized in the `version_groups` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("version_groups")
    val versionGroups: List<VersionGroupSummary>,
    /** Optional `boolean` value serialized in the `is_main_series` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("is_main_series")
    val isMainSeries: Boolean? = null,
)

/** Typed representation of the `PokedexName` API schema. */
data class PokedexName(
    /** Required `string` value serialized in the `name` wire field. */
    val name: String,
    /** Required object value serialized in the `language` wire field. */
    val language: LanguageSummary,
)

/** Typed representation of the `PokemonDexNumber` API schema. */
data class PokemonDexNumber(
    /** Required `integer` value serialized in the `entry_number` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("entry_number") val entryNumber: Int,
    /** Required object value serialized in the `pokemon_species` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("pokemon_species")
    val pokemonSpecies: PokemonSpeciesSummary,
)

/**
 * Should have a link to Version Group info but the Circular dependency and compilation order fight
 * eachother and I'm not sure how to add anything other than a hyperlink
 */
data class VersionDetail(
    /** Required `integer` value serialized in the `id` wire field. */
    val id: Int,
    /** Required `string` value serialized in the `name` wire field. */
    val name: String,
    /** Required array value serialized in the `names` wire field. */
    val names: List<VersionName>,
    /** Required object value serialized in the `version_group` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("version_group")
    val versionGroup: VersionGroupSummary,
)

/** Typed representation of the `VersionGroupDetail` API schema. */
data class VersionGroupDetail(
    /** Required `integer` value serialized in the `id` wire field. */
    val id: Int,
    /** Required `string` value serialized in the `name` wire field. */
    val name: String,
    /** Required object value serialized in the `generation` wire field. */
    val generation: GenerationSummary,
    /** Required array value serialized in the `move_learn_methods` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("move_learn_methods")
    val moveLearnMethods: List<MoveLearnMethodSummary>,
    /** Required array value serialized in the `pokedexes` wire field. */
    val pokedexes: List<PokedexSummary>,
    /** Required array value serialized in the `regions` wire field. */
    val regions: List<RegionSummary>,
    /** Required array value serialized in the `versions` wire field. */
    val versions: List<VersionSummary>,
    /** Optional `integer` value serialized in the `order` wire field. */
    val order: Int? = null,
)

/** Typed representation of the `VersionName` API schema. */
data class VersionName(
    /** Required `string` value serialized in the `name` wire field. */
    val name: String,
    /** Required object value serialized in the `language` wire field. */
    val language: LanguageSummary,
)
