// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk.models

/** Serializer for the Type resource */
data class TypeDetail(
    /** Required `integer` value serialized in the `id` wire field. */
    val id: Int,
    /** Required `string` value serialized in the `name` wire field. */
    val name: String,
    /** Required API value serialized in the `damage_relations` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("damage_relations")
    val damageRelations: TypeRelationships,
    /** Required array value serialized in the `past_damage_relations` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("past_damage_relations")
    val pastDamageRelations: List<TypePastRelationships>,
    /** Required array value serialized in the `game_indices` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("game_indices")
    val gameIndices: List<TypeGameIndex>,
    /** Required object value serialized in the `generation` wire field. */
    val generation: GenerationSummary,
    /** Required object value serialized in the `move_damage_class` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("move_damage_class")
    val moveDamageClass: MoveDamageClassSummary,
    /** Required array value serialized in the `names` wire field. */
    val names: List<TypeName>,
    /** Required array value serialized in the `pokemon` wire field. */
    val pokemon: List<TypePokemon>,
    /** Required array value serialized in the `moves` wire field. */
    val moves: List<MoveSummary>,
    /** Required API value serialized in the `sprites` wire field. */
    val sprites: TypeSprite,
)

/** Typed representation of the `TypeGameIndex` API schema. */
data class TypeGameIndex(
    /** Required `integer` value serialized in the `game_index` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("game_index") val gameIndex: Int,
    /** Required object value serialized in the `generation` wire field. */
    val generation: GenerationSummary,
)

/** Typed representation of the `TypeName` API schema. */
data class TypeName(
    /** Required `string` value serialized in the `name` wire field. */
    val name: String,
    /** Required object value serialized in the `language` wire field. */
    val language: LanguageSummary,
)

/** Typed representation of the `TypePastRelationships` API schema. */
data class TypePastRelationships(
    /** Required object value serialized in the `generation` wire field. */
    val generation: GenerationSummary,
    /** Required object value serialized in the `damage_relations` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("damage_relations")
    val damageRelations: TypeRelationships,
)

/** Typed representation of the `TypePokemon` API schema. */
data class TypePokemon(
    /** Required `integer` value serialized in the `slot` wire field. */
    val slot: Int,
    /** Required object value serialized in the `pokemon` wire field. */
    val pokemon: PokemonSummary,
)

/** Typed representation of the `TypeRelationships` API schema. */
data class TypeRelationships(
    /** Required array value serialized in the `no_damage_to` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("no_damage_to")
    val noDamageTo: List<TypeSummary>,
    /** Required array value serialized in the `half_damage_to` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("half_damage_to")
    val halfDamageTo: List<TypeSummary>,
    /** Required array value serialized in the `double_damage_to` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("double_damage_to")
    val doubleDamageTo: List<TypeSummary>,
    /** Required array value serialized in the `no_damage_from` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("no_damage_from")
    val noDamageFrom: List<TypeSummary>,
    /** Required array value serialized in the `half_damage_from` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("half_damage_from")
    val halfDamageFrom: List<TypeSummary>,
    /** Required array value serialized in the `double_damage_from` wire field. */
    @com.fasterxml.jackson.annotation.JsonProperty("double_damage_from")
    val doubleDamageFrom: List<TypeSummary>,
)

/** Typed representation of the `TypeSprite` API schema. */
data class TypeSprite(
    /** Required API value serialized in the `sprites` wire field. */
    val sprites: Any?
)
