// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dev.octri.demo.pokeapiUnofficialSdk.models

/**
 * Typed representation of the `Experience` API schema.
 */
data class Experience(
    /**
     * Required `integer` value serialized in the `level` wire field.
     */
    val level: Int,
    /**
     * Required `integer` value serialized in the `experience` wire field.
     */
    val experience: Int
)
