// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dev.octri.demo.pokeapiUnofficialSdk.models

/**
 * Typed representation of the `MoveBattleStyleDetail` API schema.
 */
data class MoveBattleStyleDetail(
    /**
     * Required `integer` value serialized in the `id` wire field.
     */
    val id: Int,
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required array value serialized in the `names` wire field.
     */
    val names: List<MoveBattleStyleName>
)

/**
 * Typed representation of the `MoveBattleStyleName` API schema.
 */
data class MoveBattleStyleName(
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary
)

/**
 * Typed representation of the `MoveChange` API schema.
 */
data class MoveChange(
    /**
     * Required `integer` value serialized in the `effect_chance` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("effect_chance") val effectChance: Int,
    /**
     * Required array value serialized in the `effect_entries` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("effect_entries") val effectEntries: List<MoveEffectEffectText>,
    /**
     * Required object value serialized in the `type` wire field.
     */
    val type: TypeSummary,
    /**
     * Required object value serialized in the `version_group` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("version_group") val versionGroup: VersionGroupSummary,
    /**
     * Optional `integer` value serialized in the `accuracy` wire field.
     */
    val accuracy: Int? = null,
    /**
     * Optional `integer` value serialized in the `power` wire field.
     */
    val power: Int? = null,
    /**
     * Optional `integer` value serialized in the `pp` wire field.
     */
    val pp: Int? = null
)

/**
 * Typed representation of the `MoveCombos` API schema.
 */
data class MoveCombos(
    /**
     * Required object value serialized in the `normal` wire field.
     */
    val normal: MoveComboUsage,
    /**
     * Required object value serialized in the `super` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("super") val `super`: MoveComboUsage
)

/**
 * Typed representation of the `MoveComboUsage` API schema.
 */
data class MoveComboUsage(
    /**
     * Required array value serialized in the `use_before` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("use_before") val useBefore: List<MoveSummary>?,
    /**
     * Required array value serialized in the `use_after` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("use_after") val useAfter: List<MoveSummary>?
)

/**
 * Typed representation of the `MoveDetail` API schema.
 */
data class MoveDetail(
    /**
     * Required `integer` value serialized in the `id` wire field.
     */
    val id: Int,
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required `integer` value serialized in the `effect_chance` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("effect_chance") val effectChance: Int,
    /**
     * Required API value serialized in the `contest_combos` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("contest_combos") val contestCombos: MoveCombos?,
    /**
     * Required object value serialized in the `contest_type` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("contest_type") val contestType: ContestTypeSummary,
    /**
     * Required object value serialized in the `contest_effect` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("contest_effect") val contestEffect: ContestEffectSummary,
    /**
     * Required object value serialized in the `damage_class` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("damage_class") val damageClass: MoveDamageClassSummary,
    /**
     * Required array value serialized in the `effect_entries` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("effect_entries") val effectEntries: List<MoveEffectEffectText>,
    /**
     * Required array value serialized in the `effect_changes` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("effect_changes") val effectChanges: List<MoveEffectChange>,
    /**
     * Required object value serialized in the `generation` wire field.
     */
    val generation: GenerationSummary,
    /**
     * Required API value serialized in the `meta` wire field.
     */
    val meta: MoveMeta,
    /**
     * Required array value serialized in the `names` wire field.
     */
    val names: List<MoveName>,
    /**
     * Required array value serialized in the `past_values` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("past_values") val pastValues: List<MoveChange>,
    /**
     * Required array value serialized in the `stat_changes` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("stat_changes") val statChanges: List<MoveMetaStatChange>,
    /**
     * Required object value serialized in the `super_contest_effect` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("super_contest_effect") val superContestEffect: SuperContestEffectSummary,
    /**
     * Required object value serialized in the `target` wire field.
     */
    val target: MoveTargetSummary,
    /**
     * Required object value serialized in the `type` wire field.
     */
    val type: TypeSummary,
    /**
     * Required array value serialized in the `machines` wire field.
     */
    val machines: List<ItemMachine>,
    /**
     * Required array value serialized in the `flavor_text_entries` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("flavor_text_entries") val flavorTextEntries: List<MoveFlavorText>,
    /**
     * Required array value serialized in the `learned_by_pokemon` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("learned_by_pokemon") val learnedByPokemon: List<PokemonSummary>,
    /**
     * Optional `integer` value serialized in the `accuracy` wire field.
     */
    val accuracy: Int? = null,
    /**
     * Optional `integer` value serialized in the `pp` wire field.
     */
    val pp: Int? = null,
    /**
     * Optional `integer` value serialized in the `priority` wire field.
     */
    val priority: Int? = null,
    /**
     * Optional `integer` value serialized in the `power` wire field.
     */
    val power: Int? = null
)

/**
 * Typed representation of the `MoveEffectChange` API schema.
 */
data class MoveEffectChange(
    /**
     * Required object value serialized in the `version_group` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("version_group") val versionGroup: VersionGroupSummary,
    /**
     * Required array value serialized in the `effect_entries` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("effect_entries") val effectEntries: List<MoveEffectChangeEffectText>
)

/**
 * Typed representation of the `MoveEffectChangeEffectText` API schema.
 */
data class MoveEffectChangeEffectText(
    /**
     * Required `string` value serialized in the `effect` wire field.
     */
    val effect: String,
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary
)

/**
 * Typed representation of the `MoveEffectEffectText` API schema.
 */
data class MoveEffectEffectText(
    /**
     * Required `string` value serialized in the `effect` wire field.
     */
    val effect: String,
    /**
     * Required `string` value serialized in the `short_effect` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("short_effect") val shortEffect: String,
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary
)

/**
 * Typed representation of the `MoveFlavorText` API schema.
 */
data class MoveFlavorText(
    /**
     * Required `string` value serialized in the `flavor_text` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("flavor_text") val flavorText: String,
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary,
    /**
     * Required object value serialized in the `version_group` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("version_group") val versionGroup: VersionGroupSummary
)

/**
 * Typed representation of the `MoveLearnMethodDescription` API schema.
 */
data class MoveLearnMethodDescription(
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary,
    /**
     * Optional `string` value serialized in the `description` wire field.
     */
    val description: String? = null
)

/**
 * Typed representation of the `MoveLearnMethodDetail` API schema.
 */
data class MoveLearnMethodDetail(
    /**
     * Required `integer` value serialized in the `id` wire field.
     */
    val id: Int,
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required array value serialized in the `names` wire field.
     */
    val names: List<MoveLearnMethodName>,
    /**
     * Required array value serialized in the `descriptions` wire field.
     */
    val descriptions: List<MoveLearnMethodDescription>,
    /**
     * Required array value serialized in the `version_groups` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("version_groups") val versionGroups: List<VersionGroupSummary>
)

/**
 * Typed representation of the `MoveLearnMethodName` API schema.
 */
data class MoveLearnMethodName(
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary
)

/**
 * Typed representation of the `MoveMeta` API schema.
 */
data class MoveMeta(
    /**
     * Required object value serialized in the `ailment` wire field.
     */
    val ailment: MoveMetaAilmentSummary,
    /**
     * Required object value serialized in the `category` wire field.
     */
    val category: MoveMetaCategorySummary,
    /**
     * Optional `integer` value serialized in the `min_hits` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("min_hits") val minHits: Int? = null,
    /**
     * Optional `integer` value serialized in the `max_hits` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("max_hits") val maxHits: Int? = null,
    /**
     * Optional `integer` value serialized in the `min_turns` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("min_turns") val minTurns: Int? = null,
    /**
     * Optional `integer` value serialized in the `max_turns` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("max_turns") val maxTurns: Int? = null,
    /**
     * Optional `integer` value serialized in the `drain` wire field.
     */
    val drain: Int? = null,
    /**
     * Optional `integer` value serialized in the `healing` wire field.
     */
    val healing: Int? = null,
    /**
     * Optional `integer` value serialized in the `crit_rate` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("crit_rate") val critRate: Int? = null,
    /**
     * Optional `integer` value serialized in the `ailment_chance` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("ailment_chance") val ailmentChance: Int? = null,
    /**
     * Optional `integer` value serialized in the `flinch_chance` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("flinch_chance") val flinchChance: Int? = null,
    /**
     * Optional `integer` value serialized in the `stat_chance` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("stat_chance") val statChance: Int? = null
)

/**
 * Typed representation of the `MoveMetaAilmentDetail` API schema.
 */
data class MoveMetaAilmentDetail(
    /**
     * Required `integer` value serialized in the `id` wire field.
     */
    val id: Int,
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required array value serialized in the `moves` wire field.
     */
    val moves: List<MoveSummary>,
    /**
     * Required array value serialized in the `names` wire field.
     */
    val names: List<MoveMetaAilmentName>
)

/**
 * Typed representation of the `MoveMetaAilmentName` API schema.
 */
data class MoveMetaAilmentName(
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary
)

/**
 * Typed representation of the `MoveMetaAilmentSummary` API schema.
 */
data class MoveMetaAilmentSummary(
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required `uri`-formatted value serialized in the `url` wire field.
     */
    val url: String
)

/**
 * Typed representation of the `MoveMetaCategoryDescription` API schema.
 */
data class MoveMetaCategoryDescription(
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary,
    /**
     * Optional `string` value serialized in the `description` wire field.
     */
    val description: String? = null
)

/**
 * Typed representation of the `MoveMetaCategoryDetail` API schema.
 */
data class MoveMetaCategoryDetail(
    /**
     * Required `integer` value serialized in the `id` wire field.
     */
    val id: Int,
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required array value serialized in the `descriptions` wire field.
     */
    val descriptions: List<MoveMetaCategoryDescription>,
    /**
     * Required array value serialized in the `moves` wire field.
     */
    val moves: List<MoveSummary>
)

/**
 * Typed representation of the `MoveMetaCategorySummary` API schema.
 */
data class MoveMetaCategorySummary(
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required `uri`-formatted value serialized in the `url` wire field.
     */
    val url: String
)

/**
 * Typed representation of the `MoveMetaStatChange` API schema.
 */
data class MoveMetaStatChange(
    /**
     * Required `integer` value serialized in the `change` wire field.
     */
    val change: Int,
    /**
     * Required object value serialized in the `stat` wire field.
     */
    val stat: StatSummary
)

/**
 * Typed representation of the `MoveName` API schema.
 */
data class MoveName(
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary
)

/**
 * Typed representation of the `MoveTargetDescription` API schema.
 */
data class MoveTargetDescription(
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary,
    /**
     * Optional `string` value serialized in the `description` wire field.
     */
    val description: String? = null
)

/**
 * Typed representation of the `MoveTargetDetail` API schema.
 */
data class MoveTargetDetail(
    /**
     * Required `integer` value serialized in the `id` wire field.
     */
    val id: Int,
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required array value serialized in the `descriptions` wire field.
     */
    val descriptions: List<MoveTargetDescription>,
    /**
     * Required array value serialized in the `moves` wire field.
     */
    val moves: List<MoveSummary>,
    /**
     * Required array value serialized in the `names` wire field.
     */
    val names: List<MoveTargetName>
)

/**
 * Typed representation of the `MoveTargetName` API schema.
 */
data class MoveTargetName(
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary
)

/**
 * Typed representation of the `MoveTargetSummary` API schema.
 */
data class MoveTargetSummary(
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required `uri`-formatted value serialized in the `url` wire field.
     */
    val url: String
)

/**
 * Typed representation of the `PaginatedMoveBattleStyleSummaryList` API schema.
 */
data class PaginatedMoveBattleStyleSummaryList(
    /**
     * Required `integer` value serialized in the `count` wire field.
     */
    val count: Int,
    /**
     * Required array value serialized in the `results` wire field.
     */
    val results: List<MoveBattleStyleSummary>,
    /**
     * Optional `uri`-formatted value serialized in the `next` wire field.
     */
    val next: String? = null,
    /**
     * Optional `uri`-formatted value serialized in the `previous` wire field.
     */
    val previous: String? = null
)

/**
 * Typed representation of the `PaginatedMoveLearnMethodSummaryList` API schema.
 */
data class PaginatedMoveLearnMethodSummaryList(
    /**
     * Required `integer` value serialized in the `count` wire field.
     */
    val count: Int,
    /**
     * Required array value serialized in the `results` wire field.
     */
    val results: List<MoveLearnMethodSummary>,
    /**
     * Optional `uri`-formatted value serialized in the `next` wire field.
     */
    val next: String? = null,
    /**
     * Optional `uri`-formatted value serialized in the `previous` wire field.
     */
    val previous: String? = null
)
