// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dev.octri.demo.pokeapiUnofficialSdk.models

/**
 * Typed representation of the `MachineDetail` API schema.
 */
data class MachineDetail(
    /**
     * Required `integer` value serialized in the `id` wire field.
     */
    val id: Int,
    /**
     * Required object value serialized in the `item` wire field.
     */
    val item: ItemSummary,
    /**
     * Required object value serialized in the `version_group` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("version_group") val versionGroup: VersionGroupSummary,
    /**
     * Required object value serialized in the `move` wire field.
     */
    val move: MoveSummary
)

/**
 * Typed representation of the `PaginatedMachineSummaryList` API schema.
 */
data class PaginatedMachineSummaryList(
    /**
     * Required `integer` value serialized in the `count` wire field.
     */
    val count: Int,
    /**
     * Required array value serialized in the `results` wire field.
     */
    val results: List<MachineSummary>,
    /**
     * Optional `uri`-formatted value serialized in the `next` wire field.
     */
    val next: String? = null,
    /**
     * Optional `uri`-formatted value serialized in the `previous` wire field.
     */
    val previous: String? = null
)
