// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dev.octri.demo.pokeapiUnofficialSdk.models

/**
 * Typed representation of the `NatureBattleStylePreference` API schema.
 */
data class NatureBattleStylePreference(
    /**
     * Required `integer` value serialized in the `low_hp_preference` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("low_hp_preference") val lowHpPreference: Int,
    /**
     * Required `integer` value serialized in the `high_hp_preference` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("high_hp_preference") val highHpPreference: Int,
    /**
     * Required object value serialized in the `move_battle_style` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("move_battle_style") val moveBattleStyle: MoveBattleStyleSummary
)

/**
 * Typed representation of the `NatureDetail` API schema.
 */
data class NatureDetail(
    /**
     * Required `integer` value serialized in the `id` wire field.
     */
    val id: Int,
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required object value serialized in the `decreased_stat` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("decreased_stat") val decreasedStat: StatSummary,
    /**
     * Required object value serialized in the `increased_stat` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("increased_stat") val increasedStat: StatSummary,
    /**
     * Required object value serialized in the `likes_flavor` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("likes_flavor") val likesFlavor: BerryFlavorSummary,
    /**
     * Required object value serialized in the `hates_flavor` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("hates_flavor") val hatesFlavor: BerryFlavorSummary,
    /**
     * Required array value serialized in the `berries` wire field.
     */
    val berries: List<BerrySummary>,
    /**
     * Required array value serialized in the `pokeathlon_stat_changes` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("pokeathlon_stat_changes") val pokeathlonStatChanges: List<NaturePokeathlonStat>,
    /**
     * Required array value serialized in the `move_battle_style_preferences` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("move_battle_style_preferences") val moveBattleStylePreferences: List<NatureBattleStylePreference>,
    /**
     * Required array value serialized in the `names` wire field.
     */
    val names: List<NatureName>
)

/**
 * Typed representation of the `NatureName` API schema.
 */
data class NatureName(
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary
)

/**
 * Typed representation of the `NaturePokeathlonStat` API schema.
 */
data class NaturePokeathlonStat(
    /**
     * Required `integer` value serialized in the `max_change` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("max_change") val maxChange: Int,
    /**
     * Required object value serialized in the `pokeathlon_stat` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("pokeathlon_stat") val pokeathlonStat: PokeathlonStatSummary
)
