// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dev.octri.demo.pokeapiUnofficialSdk.models

/** Typed representation of the `PaginatedAbilitySummaryList` API schema. */
data class PaginatedAbilitySummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<AbilitySummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedCharacteristicSummaryList` API schema. */
data class PaginatedCharacteristicSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<CharacteristicSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedEggGroupSummaryList` API schema. */
data class PaginatedEggGroupSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<EggGroupSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedGenderSummaryList` API schema. */
data class PaginatedGenderSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<GenderSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedGrowthRateSummaryList` API schema. */
data class PaginatedGrowthRateSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<GrowthRateSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedMoveDamageClassSummaryList` API schema. */
data class PaginatedMoveDamageClassSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<MoveDamageClassSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedNatureSummaryList` API schema. */
data class PaginatedNatureSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<NatureSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedPokeathlonStatSummaryList` API schema. */
data class PaginatedPokeathlonStatSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<PokeathlonStatSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedPokemonColorSummaryList` API schema. */
data class PaginatedPokemonColorSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<PokemonColorSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedPokemonFormSummaryList` API schema. */
data class PaginatedPokemonFormSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<PokemonFormSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedPokemonHabitatSummaryList` API schema. */
data class PaginatedPokemonHabitatSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<PokemonHabitatSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedPokemonShapeSummaryList` API schema. */
data class PaginatedPokemonShapeSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<PokemonShapeSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedPokemonSpeciesSummaryList` API schema. */
data class PaginatedPokemonSpeciesSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<PokemonSpeciesSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedPokemonSummaryList` API schema. */
data class PaginatedPokemonSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<PokemonSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedStatSummaryList` API schema. */
data class PaginatedStatSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<StatSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)

/** Typed representation of the `PaginatedTypeSummaryList` API schema. */
data class PaginatedTypeSummaryList(
    /** Required `integer` value serialized in the `count` wire field. */
    val count: Int,
    /** Required array value serialized in the `results` wire field. */
    val results: List<TypeSummary>,
    /** Optional `uri`-formatted value serialized in the `next` wire field. */
    val next: String? = null,
    /** Optional `uri`-formatted value serialized in the `previous` wire field. */
    val previous: String? = null,
)
