// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package dev.octri.demo.pokeapiUnofficialSdk.models

/**
 * Typed representation of the `PokemonSpeciesDetail` API schema.
 */
data class PokemonSpeciesDetail(
    /**
     * Required `integer` value serialized in the `id` wire field.
     */
    val id: Int,
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required object value serialized in the `growth_rate` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("growth_rate") val growthRate: GrowthRateSummary,
    /**
     * Required array value serialized in the `pokedex_numbers` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("pokedex_numbers") val pokedexNumbers: List<PokemonDexEntry>,
    /**
     * Required array value serialized in the `egg_groups` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("egg_groups") val eggGroups: List<EggGroupSummary>,
    /**
     * Required object value serialized in the `color` wire field.
     */
    val color: PokemonColorSummary,
    /**
     * Required object value serialized in the `shape` wire field.
     */
    val shape: PokemonShapeSummary,
    /**
     * Required object value serialized in the `evolves_from_species` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("evolves_from_species") val evolvesFromSpecies: PokemonSpeciesSummary,
    /**
     * Required object value serialized in the `evolution_chain` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("evolution_chain") val evolutionChain: EvolutionChainSummary,
    /**
     * Required object value serialized in the `habitat` wire field.
     */
    val habitat: PokemonHabitatSummary,
    /**
     * Required object value serialized in the `generation` wire field.
     */
    val generation: GenerationSummary,
    /**
     * Required array value serialized in the `names` wire field.
     */
    val names: List<PokemonSpeciesName>,
    /**
     * Required array value serialized in the `pal_park_encounters` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("pal_park_encounters") val palParkEncounters: List<PokemonSpeciesPalParkEncounter>,
    /**
     * Required array value serialized in the `form_descriptions` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("form_descriptions") val formDescriptions: List<PokemonSpeciesDescription>,
    /**
     * Required array value serialized in the `flavor_text_entries` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("flavor_text_entries") val flavorTextEntries: List<PokemonSpeciesFlavorText>,
    /**
     * Required array value serialized in the `genera` wire field.
     */
    val genera: List<PokemonSpeciesGenus>,
    /**
     * Required array value serialized in the `varieties` wire field.
     */
    val varieties: List<PokemonSpeciesVariety>,
    /**
     * Optional `integer` value serialized in the `order` wire field.
     */
    val order: Int? = null,
    /**
     * Optional `integer` value serialized in the `gender_rate` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("gender_rate") val genderRate: Int? = null,
    /**
     * Optional `integer` value serialized in the `capture_rate` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("capture_rate") val captureRate: Int? = null,
    /**
     * Optional `integer` value serialized in the `base_happiness` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("base_happiness") val baseHappiness: Int? = null,
    /**
     * Optional `boolean` value serialized in the `is_baby` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("is_baby") val isBaby: Boolean? = null,
    /**
     * Optional `boolean` value serialized in the `is_legendary` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("is_legendary") val isLegendary: Boolean? = null,
    /**
     * Optional `boolean` value serialized in the `is_mythical` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("is_mythical") val isMythical: Boolean? = null,
    /**
     * Optional `integer` value serialized in the `hatch_counter` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("hatch_counter") val hatchCounter: Int? = null,
    /**
     * Optional `boolean` value serialized in the `has_gender_differences` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("has_gender_differences") val hasGenderDifferences: Boolean? = null,
    /**
     * Optional `boolean` value serialized in the `forms_switchable` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("forms_switchable") val formsSwitchable: Boolean? = null
)

/**
 * Typed representation of the `PokemonSpeciesFlavorText` API schema.
 */
data class PokemonSpeciesFlavorText(
    /**
     * Required `string` value serialized in the `flavor_text` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("flavor_text") val flavorText: String,
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary,
    /**
     * Required object value serialized in the `version` wire field.
     */
    val version: VersionSummary
)

/**
 * Typed representation of the `PokemonSpeciesGenus` API schema.
 */
data class PokemonSpeciesGenus(
    /**
     * Required `string` value serialized in the `genus` wire field.
     */
    val genus: String,
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary
)

/**
 * Typed representation of the `PokemonSpeciesName` API schema.
 */
data class PokemonSpeciesName(
    /**
     * Required `string` value serialized in the `name` wire field.
     */
    val name: String,
    /**
     * Required object value serialized in the `language` wire field.
     */
    val language: LanguageSummary
)

/**
 * Typed representation of the `PokemonSpeciesPalParkEncounter` API schema.
 */
data class PokemonSpeciesPalParkEncounter(
    /**
     * Required `integer` value serialized in the `rate` wire field.
     */
    val rate: Int,
    /**
     * Required object value serialized in the `area` wire field.
     */
    val area: PalParkAreaSummary,
    /**
     * Optional `integer` value serialized in the `base_score` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("base_score") val baseScore: Int? = null
)

/**
 * Typed representation of the `PokemonSpeciesVariety` API schema.
 */
data class PokemonSpeciesVariety(
    /**
     * Required `boolean` value serialized in the `is_default` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("is_default") val isDefault: Boolean,
    /**
     * Required object value serialized in the `pokemon` wire field.
     */
    val pokemon: PokemonSummary
)

/**
 * Typed representation of the `PokemonSprites` API schema.
 */
data class PokemonSprites(
    /**
     * Required `string` value serialized in the `front_default` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("front_default") val frontDefault: String?
)

/**
 * Typed representation of the `PokemonStat` API schema.
 */
data class PokemonStat(
    /**
     * Required `integer` value serialized in the `base_stat` wire field.
     */
    @com.fasterxml.jackson.annotation.JsonProperty("base_stat") val baseStat: Int,
    /**
     * Required `integer` value serialized in the `effort` wire field.
     */
    val effort: Int,
    /**
     * Required object value serialized in the `stat` wire field.
     */
    val stat: StatSummary
)

/**
 * Typed representation of the `PokemonType` API schema.
 */
data class PokemonType(
    /**
     * Required `integer` value serialized in the `slot` wire field.
     */
    val slot: Int,
    /**
     * Required object value serialized in the `type` wire field.
     */
    val type: TypeSummary
)
