// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk.methods

import sdk.AbilityDetail
import sdk.AbilitySummary
import sdk.CharacteristicDetail
import sdk.CharacteristicSummary
import sdk.ClientConfig
import sdk.EggGroupDetail
import sdk.EggGroupSummary
import sdk.GenderDetail
import sdk.GenderSummary
import sdk.GrowthRateDetail
import sdk.GrowthRateSummary
import sdk.MoveDamageClassDetail
import sdk.MoveDamageClassSummary
import sdk.NatureDetail
import sdk.NatureSummary
import sdk.PaginatedAbilitySummaryList
import sdk.PaginatedCharacteristicSummaryList
import sdk.PaginatedEggGroupSummaryList
import sdk.PaginatedGenderSummaryList
import sdk.PaginatedGrowthRateSummaryList
import sdk.PaginatedMoveDamageClassSummaryList
import sdk.PaginatedNatureSummaryList
import sdk.PaginatedPokeathlonStatSummaryList
import sdk.PaginatedPokemonColorSummaryList
import sdk.PaginatedPokemonFormSummaryList
import sdk.PaginatedPokemonHabitatSummaryList
import sdk.PaginatedPokemonShapeSummaryList
import sdk.PaginatedPokemonSpeciesSummaryList
import sdk.PaginatedPokemonSummaryList
import sdk.PaginatedStatSummaryList
import sdk.PaginatedTypeSummaryList
import sdk.PokeathlonStatDetail
import sdk.PokeathlonStatSummary
import sdk.PokemonColorDetail
import sdk.PokemonColorSummary
import sdk.PokemonDetail
import sdk.PokemonFormDetail
import sdk.PokemonFormSummary
import sdk.PokemonHabitatDetail
import sdk.PokemonHabitatSummary
import sdk.PokemonShapeDetail
import sdk.PokemonShapeSummary
import sdk.PokemonSpeciesDetail
import sdk.PokemonSpeciesSummary
import sdk.PokemonSummary
import sdk.RequestOptions
import sdk.StatDetail
import sdk.StatSummary
import sdk.TypeDetail
import sdk.TypeSummary

object Pokemon {
    data class AbilityListPage(
        val data: PaginatedAbilitySummaryList,
        val items: List<AbilitySummary>,
        val hasMore: Boolean,
    )

    data class CharacteristicListPage(
        val data: PaginatedCharacteristicSummaryList,
        val items: List<CharacteristicSummary>,
        val hasMore: Boolean,
    )

    data class EggGroupListPage(
        val data: PaginatedEggGroupSummaryList,
        val items: List<EggGroupSummary>,
        val hasMore: Boolean,
    )

    data class GenderListPage(
        val data: PaginatedGenderSummaryList,
        val items: List<GenderSummary>,
        val hasMore: Boolean,
    )

    data class GrowthRateListPage(
        val data: PaginatedGrowthRateSummaryList,
        val items: List<GrowthRateSummary>,
        val hasMore: Boolean,
    )

    data class MoveDamageClassListPage(
        val data: PaginatedMoveDamageClassSummaryList,
        val items: List<MoveDamageClassSummary>,
        val hasMore: Boolean,
    )

    data class NatureListPage(
        val data: PaginatedNatureSummaryList,
        val items: List<NatureSummary>,
        val hasMore: Boolean,
    )

    data class PokemonListPage(
        val data: PaginatedPokemonSummaryList,
        val items: List<PokemonSummary>,
        val hasMore: Boolean,
    )

    data class PokemonColorListPage(
        val data: PaginatedPokemonColorSummaryList,
        val items: List<PokemonColorSummary>,
        val hasMore: Boolean,
    )

    data class PokemonFormListPage(
        val data: PaginatedPokemonFormSummaryList,
        val items: List<PokemonFormSummary>,
        val hasMore: Boolean,
    )

    data class PokemonHabitatListPage(
        val data: PaginatedPokemonHabitatSummaryList,
        val items: List<PokemonHabitatSummary>,
        val hasMore: Boolean,
    )

    data class PokemonShapeListPage(
        val data: PaginatedPokemonShapeSummaryList,
        val items: List<PokemonShapeSummary>,
        val hasMore: Boolean,
    )

    data class PokemonSpeciesListPage(
        val data: PaginatedPokemonSpeciesSummaryList,
        val items: List<PokemonSpeciesSummary>,
        val hasMore: Boolean,
    )

    data class PokeathlonStatListPage(
        val data: PaginatedPokeathlonStatSummaryList,
        val items: List<PokeathlonStatSummary>,
        val hasMore: Boolean,
    )

    data class StatListPage(
        val data: PaginatedStatSummaryList,
        val items: List<StatSummary>,
        val hasMore: Boolean,
    )

    data class TypeListPage(
        val data: PaginatedTypeSummaryList,
        val items: List<TypeSummary>,
        val hasMore: Boolean,
    )

    /**
     * Lists abilities, which provide passive effects for Pokémon in battle or in the overworld. Use `limit` and `offset` to select a result window, and `q` to filter by name when running a local API instance.
     */
    fun abilityList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedAbilitySummaryList =
        sdk.methods.PokemonAbilityListOperation.abilityList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists abilities, which provide passive effects for Pokémon in battle or in the overworld. Use `limit` and `offset` to select a result window, and `q` to filter by name when running a local API instance.
     */
    fun abilityListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (AbilitySummary) -> Boolean) =
        sdk.methods.PokemonAbilityListOperation.abilityListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists abilities, which provide passive effects for Pokémon in battle or in the overworld. Use `limit` and `offset` to select a result window, and `q` to filter by name when running a local API instance.
     */
    fun abilityListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (AbilityListPage) -> Boolean) =
        sdk.methods.PokemonAbilityListOperation.abilityListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a single ability and its Pokémon, generation, effect, and localized text data. Supply the ability's `id` as a string or integer to look up the record.
     */
    fun abilityRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): AbilityDetail =
        sdk.methods.PokemonAbilityRetrieveOperation.abilityRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists characteristics that indicate which stat contains a Pokémon's highest individual value (IV). Use `limit` and `offset` to select a result window, and `q` to filter characteristics by name on a local API instance.
     */
    fun characteristicList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedCharacteristicSummaryList =
        sdk.methods.PokemonCharacteristicListOperation.characteristicList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists characteristics that indicate which stat contains a Pokémon's highest individual value (IV). Use `limit` and `offset` to select a result window, and `q` to filter characteristics by name on a local API instance.
     */
    fun characteristicListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (CharacteristicSummary) -> Boolean) =
        sdk.methods.PokemonCharacteristicListOperation.characteristicListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists characteristics that indicate which stat contains a Pokémon's highest individual value (IV). Use `limit` and `offset` to select a result window, and `q` to filter characteristics by name on a local API instance.
     */
    fun characteristicListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (CharacteristicListPage) -> Boolean) =
        sdk.methods.PokemonCharacteristicListOperation.characteristicListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves the characteristic that describes which stat contains a Pokémon's highest IV. Use the `id` path parameter to select a characteristic and read its gene modulo, possible values, highest stat, and localized descriptions.
     */
    fun characteristicRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): CharacteristicDetail =
        sdk.methods.PokemonCharacteristicRetrieveOperation.characteristicRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists egg groups, which determine which Pokémon can interbreed. Use `limit` and `offset` to control the result page, or filter by name with the locally available, case-insensitive `q` query.
     */
    fun eggGroupList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedEggGroupSummaryList =
        sdk.methods.PokemonEggGroupListOperation.eggGroupList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists egg groups, which determine which Pokémon can interbreed. Use `limit` and `offset` to control the result page, or filter by name with the locally available, case-insensitive `q` query.
     */
    fun eggGroupListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (EggGroupSummary) -> Boolean) =
        sdk.methods.PokemonEggGroupListOperation.eggGroupListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists egg groups, which determine which Pokémon can interbreed. Use `limit` and `offset` to control the result page, or filter by name with the locally available, case-insensitive `q` query.
     */
    fun eggGroupListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (EggGroupListPage) -> Boolean) =
        sdk.methods.PokemonEggGroupListOperation.eggGroupListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves an egg group that determines which Pokémon can interbreed. Use the `id` path parameter to view the group's name, localized names, and associated Pokémon species.
     */
    fun eggGroupRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): EggGroupDetail =
        sdk.methods.PokemonEggGroupRetrieveOperation.eggGroupRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists genders used to describe Pokémon, including gender differences relevant to breeding, appearance, and evolution. Use `q` to filter by name, or `limit` and `offset` to control the results page.
     */
    fun genderList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedGenderSummaryList =
        sdk.methods.PokemonGenderListOperation.genderList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists genders used to describe Pokémon, including gender differences relevant to breeding, appearance, and evolution. Use `q` to filter by name, or `limit` and `offset` to control the results page.
     */
    fun genderListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (GenderSummary) -> Boolean) =
        sdk.methods.PokemonGenderListOperation.genderListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists genders used to describe Pokémon, including gender differences relevant to breeding, appearance, and evolution. Use `q` to filter by name, or `limit` and `offset` to control the results page.
     */
    fun genderListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (GenderListPage) -> Boolean) =
        sdk.methods.PokemonGenderListOperation.genderListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a gender and its associated Pokémon species data. Use the `id` path parameter to view the species details and the evolution conditions associated with that gender.
     */
    fun genderRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): GenderDetail =
        sdk.methods.PokemonGenderRetrieveOperation.genderRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists growth rates that describe how Pokémon gain levels through experience. Use `q` to filter by name, or `limit` and `offset` to control the results page.
     */
    fun growthRateList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedGrowthRateSummaryList =
        sdk.methods.PokemonGrowthRateListOperation.growthRateList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists growth rates that describe how Pokémon gain levels through experience. Use `q` to filter by name, or `limit` and `offset` to control the results page.
     */
    fun growthRateListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (GrowthRateSummary) -> Boolean) =
        sdk.methods.PokemonGrowthRateListOperation.growthRateListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists growth rates that describe how Pokémon gain levels through experience. Use `q` to filter by name, or `limit` and `offset` to control the results page.
     */
    fun growthRateListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (GrowthRateListPage) -> Boolean) =
        sdk.methods.PokemonGrowthRateListOperation.growthRateListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a growth rate and the experience data associated with it. Use the `id` path parameter to view its formula, localized descriptions, level thresholds, and associated Pokémon species.
     */
    fun growthRateRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): GrowthRateDetail =
        sdk.methods.PokemonGrowthRateRetrieveOperation.growthRateRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists move damage classes, such as physical, special, or non-damaging. Use `q` to filter the results by name with a case-insensitive query; this filter is available locally but not at pokeapi.co.
     */
    fun moveDamageClassList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedMoveDamageClassSummaryList =
        sdk.methods.PokemonMoveDamageClassListOperation.moveDamageClassList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists move damage classes, such as physical, special, or non-damaging. Use `q` to filter the results by name with a case-insensitive query; this filter is available locally but not at pokeapi.co.
     */
    fun moveDamageClassListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (MoveDamageClassSummary) -> Boolean) =
        sdk.methods.PokemonMoveDamageClassListOperation.moveDamageClassListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists move damage classes, such as physical, special, or non-damaging. Use `q` to filter the results by name with a case-insensitive query; this filter is available locally but not at pokeapi.co.
     */
    fun moveDamageClassListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (MoveDamageClassListPage) -> Boolean) =
        sdk.methods.PokemonMoveDamageClassListOperation.moveDamageClassListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a move damage class, such as physical, special, or non-damaging. Use the class identifier to look up its descriptions, localized names, and associated moves.
     */
    fun moveDamageClassRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): MoveDamageClassDetail =
        sdk.methods.PokemonMoveDamageClassRetrieveOperation.moveDamageClassRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists natures, which influence how a Pokémon's stats grow. Use `q` to filter the results by name with a case-insensitive query; this filter is available locally but not at pokeapi.co.
     */
    fun natureList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedNatureSummaryList =
        sdk.methods.PokemonNatureListOperation.natureList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists natures, which influence how a Pokémon's stats grow. Use `q` to filter the results by name with a case-insensitive query; this filter is available locally but not at pokeapi.co.
     */
    fun natureListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (NatureSummary) -> Boolean) =
        sdk.methods.PokemonNatureListOperation.natureListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists natures, which influence how a Pokémon's stats grow. Use `q` to filter the results by name with a case-insensitive query; this filter is available locally but not at pokeapi.co.
     */
    fun natureListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (NatureListPage) -> Boolean) =
        sdk.methods.PokemonNatureListOperation.natureListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a nature record describing its effects on Pokémon stats, flavor preferences, and other attributes. Use the nature identifier to look up its stat changes, preferred flavors, and related preferences.
     */
    fun natureRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): NatureDetail =
        sdk.methods.PokemonNatureRetrieveOperation.natureRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists Pokémon records representing individual Pokémon and their variants. Use `limit` and `offset` to paginate the results, or use `q` to search Pokémon names when running the API locally.
     */
    fun pokemonList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedPokemonSummaryList =
        sdk.methods.PokemonListOperation.pokemonList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists Pokémon records representing individual Pokémon and their variants. Use `limit` and `offset` to paginate the results, or use `q` to search Pokémon names when running the API locally.
     */
    fun pokemonListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (PokemonSummary) -> Boolean) =
        sdk.methods.PokemonListOperation.pokemonListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists Pokémon records representing individual Pokémon and their variants. Use `limit` and `offset` to paginate the results, or use `q` to search Pokémon names when running the API locally.
     */
    fun pokemonListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (PokemonListPage) -> Boolean) =
        sdk.methods.PokemonListOperation.pokemonListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a Pokémon record with its species, abilities, forms, moves, and other game data. Use the Pokémon identifier to distinguish a specific Pokémon variant from its species record.
     */
    fun pokemonRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): PokemonDetail =
        sdk.methods.PokemonRetrieveOperation.pokemonRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists colors used to sort Pokémon in a Pokédex. Use `limit` and `offset` to paginate the results, or use `q` to search color names when running the API locally.
     */
    fun pokemonColorList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedPokemonColorSummaryList =
        sdk.methods.PokemonColorListOperation.pokemonColorList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists colors used to sort Pokémon in a Pokédex. Use `limit` and `offset` to paginate the results, or use `q` to search color names when running the API locally.
     */
    fun pokemonColorListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (PokemonColorSummary) -> Boolean) =
        sdk.methods.PokemonColorListOperation.pokemonColorListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists colors used to sort Pokémon in a Pokédex. Use `limit` and `offset` to paginate the results, or use `q` to search color names when running the API locally.
     */
    fun pokemonColorListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (PokemonColorListPage) -> Boolean) =
        sdk.methods.PokemonColorListOperation.pokemonColorListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a Pokémon color record and the species associated with that color. Use the color identifier to look up its localized names and related Pokémon species.
     */
    fun pokemonColorRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): PokemonColorDetail =
        sdk.methods.PokemonColorRetrieveOperation.pokemonColorRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists cosmetic forms in which Pokémon can appear. Use `limit` and `offset` to paginate the results, or use `q` to search form names when running the API locally.
     */
    fun pokemonFormList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedPokemonFormSummaryList =
        sdk.methods.PokemonFormListOperation.pokemonFormList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists cosmetic forms in which Pokémon can appear. Use `limit` and `offset` to paginate the results, or use `q` to search form names when running the API locally.
     */
    fun pokemonFormListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (PokemonFormSummary) -> Boolean) =
        sdk.methods.PokemonFormListOperation.pokemonFormListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists cosmetic forms in which Pokémon can appear. Use `limit` and `offset` to paginate the results, or use `q` to search form names when running the API locally.
     */
    fun pokemonFormListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (PokemonFormListPage) -> Boolean) =
        sdk.methods.PokemonFormListOperation.pokemonFormListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a Pokémon form, which represents a cosmetic variation of a Pokémon. Use `id` to select the form and inspect its Pokémon, version group, types, localized names, and trigger conditions.
     */
    fun pokemonFormRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): PokemonFormDetail =
        sdk.methods.PokemonFormRetrieveOperation.pokemonFormRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists Pokémon habitats, which describe terrain where Pokémon can be found or areas designated for rare or legendary Pokémon. Use `limit` and `offset` to page through results, or use `q` to filter by name; `q` is available only on local installations.
     */
    fun pokemonHabitatList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedPokemonHabitatSummaryList =
        sdk.methods.PokemonHabitatListOperation.pokemonHabitatList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists Pokémon habitats, which describe terrain where Pokémon can be found or areas designated for rare or legendary Pokémon. Use `limit` and `offset` to page through results, or use `q` to filter by name; `q` is available only on local installations.
     */
    fun pokemonHabitatListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (PokemonHabitatSummary) -> Boolean) =
        sdk.methods.PokemonHabitatListOperation.pokemonHabitatListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists Pokémon habitats, which describe terrain where Pokémon can be found or areas designated for rare or legendary Pokémon. Use `limit` and `offset` to page through results, or use `q` to filter by name; `q` is available only on local installations.
     */
    fun pokemonHabitatListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (PokemonHabitatListPage) -> Boolean) =
        sdk.methods.PokemonHabitatListOperation.pokemonHabitatListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a Pokémon habitat, which describes terrain where Pokémon can be found or an area designated for rare or legendary Pokémon. Use `id` to select a habitat and view its localized names and associated Pokémon species.
     */
    fun pokemonHabitatRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): PokemonHabitatDetail =
        sdk.methods.PokemonHabitatRetrieveOperation.pokemonHabitatRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists shapes used to sort Pokémon in a Pokédex. Use `limit` and `offset` to page through results, or use `q` to filter shapes by name; `q` is available only on local installations.
     */
    fun pokemonShapeList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedPokemonShapeSummaryList =
        sdk.methods.PokemonShapeListOperation.pokemonShapeList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists shapes used to sort Pokémon in a Pokédex. Use `limit` and `offset` to page through results, or use `q` to filter shapes by name; `q` is available only on local installations.
     */
    fun pokemonShapeListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (PokemonShapeSummary) -> Boolean) =
        sdk.methods.PokemonShapeListOperation.pokemonShapeListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists shapes used to sort Pokémon in a Pokédex. Use `limit` and `offset` to page through results, or use `q` to filter shapes by name; `q` is available only on local installations.
     */
    fun pokemonShapeListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (PokemonShapeListPage) -> Boolean) =
        sdk.methods.PokemonShapeListOperation.pokemonShapeListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a Pokémon shape used to sort Pokémon in a Pokédex. Use `id` to select a shape and view its localized names, alternative shape names, and associated Pokémon species.
     */
    fun pokemonShapeRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): PokemonShapeDetail =
        sdk.methods.PokemonShapeRetrieveOperation.pokemonShapeRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists Pokémon species, whose shared attributes apply across the varieties within each species. Use `limit` and `offset` to page through results, or use `q` to filter species by name; `q` is available only on local installations.
     */
    fun pokemonSpeciesList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedPokemonSpeciesSummaryList =
        sdk.methods.PokemonSpeciesListOperation.pokemonSpeciesList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists Pokémon species, whose shared attributes apply across the varieties within each species. Use `limit` and `offset` to page through results, or use `q` to filter species by name; `q` is available only on local installations.
     */
    fun pokemonSpeciesListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (PokemonSpeciesSummary) -> Boolean) =
        sdk.methods.PokemonSpeciesListOperation.pokemonSpeciesListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists Pokémon species, whose shared attributes apply across the varieties within each species. Use `limit` and `offset` to page through results, or use `q` to filter species by name; `q` is available only on local installations.
     */
    fun pokemonSpeciesListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (PokemonSpeciesListPage) -> Boolean) =
        sdk.methods.PokemonSpeciesListOperation.pokemonSpeciesListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a Pokémon species, whose attributes are shared across its Pokémon varieties. Use `id` to select a species and inspect its generation, growth rate, habitat, egg groups, Pokédex numbers, and other species attributes.
     */
    fun pokemonSpeciesRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): PokemonSpeciesDetail =
        sdk.methods.PokemonSpeciesRetrieveOperation.pokemonSpeciesRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists Pokéathlon stats, which describe different attributes of a Pokémon's performance in Pokéathlons. Use `limit` and `offset` to page through results, or use `q` to filter stats by name; `q` is available only on local installations.
     */
    fun pokeathlonStatList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedPokeathlonStatSummaryList =
        sdk.methods.PokemonPokeathlonStatListOperation.pokeathlonStatList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists Pokéathlon stats, which describe different attributes of a Pokémon's performance in Pokéathlons. Use `limit` and `offset` to page through results, or use `q` to filter stats by name; `q` is available only on local installations.
     */
    fun pokeathlonStatListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (PokeathlonStatSummary) -> Boolean) =
        sdk.methods.PokemonPokeathlonStatListOperation.pokeathlonStatListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists Pokéathlon stats, which describe different attributes of a Pokémon's performance in Pokéathlons. Use `limit` and `offset` to page through results, or use `q` to filter stats by name; `q` is available only on local installations.
     */
    fun pokeathlonStatListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (PokeathlonStatListPage) -> Boolean) =
        sdk.methods.PokemonPokeathlonStatListOperation.pokeathlonStatListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a Pokéathlon stat, which represents an attribute of a Pokémon's performance in Pokéathlons. Use `id` to select a stat and view its localized names and the natures that affect it.
     */
    fun pokeathlonStatRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): PokeathlonStatDetail =
        sdk.methods.PokemonPokeathlonStatRetrieveOperation.pokeathlonStatRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists Pokémon stats, which determine aspects of battles and have values that grow as Pokémon gain levels. Use `limit` and `offset` to control the results, or use `q` to search names case-insensitively; `q` is available only on the local API.
     */
    fun statList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedStatSummaryList =
        sdk.methods.PokemonStatListOperation.statList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists Pokémon stats, which determine aspects of battles and have values that grow as Pokémon gain levels. Use `limit` and `offset` to control the results, or use `q` to search names case-insensitively; `q` is available only on the local API.
     */
    fun statListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (StatSummary) -> Boolean) =
        sdk.methods.PokemonStatListOperation.statListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists Pokémon stats, which determine aspects of battles and have values that grow as Pokémon gain levels. Use `limit` and `offset` to control the results, or use `q` to search names case-insensitively; `q` is available only on the local API.
     */
    fun statListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (StatListPage) -> Boolean) =
        sdk.methods.PokemonStatListOperation.statListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a Pokémon stat record describing a stat's battle effects and related data. Use the `id` path parameter to identify the stat, then inspect its damage class, affecting moves, natures, and items, and associated characteristics.
     */
    fun statRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): StatDetail =
        sdk.methods.PokemonStatRetrieveOperation.statRetrieve(
            clientConfig,
            id,
            options,
        )

    /**
     * Lists Pokémon types, which describe type properties for Pokémon and their moves. Use `limit` and `offset` to control the results, or use `q` to search type names case-insensitively; `q` is available only on the local API.
     */
    fun typeList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedTypeSummaryList =
        sdk.methods.PokemonTypeListOperation.typeList(
            clientConfig,
            limit,
            offset,
            q,
            options,
        )

    /**
     * Iterates through all pages: Lists Pokémon types, which describe type properties for Pokémon and their moves. Use `limit` and `offset` to control the results, or use `q` to search type names case-insensitively; `q` is available only on the local API.
     */
    fun typeListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (TypeSummary) -> Boolean) =
        sdk.methods.PokemonTypeListOperation.typeListPaginated(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldFn,
        )

    /**
     * Lists Pokémon types, which describe type properties for Pokémon and their moves. Use `limit` and `offset` to control the results, or use `q` to search type names case-insensitively; `q` is available only on the local API.
     */
    fun typeListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (TypeListPage) -> Boolean) =
        sdk.methods.PokemonTypeListOperation.typeListPages(
            clientConfig,
            limit,
            offset,
            q,
            options,
            yieldPage,
        )

    /**
     * Retrieves a Pokémon type and its relationships with other types. Use the `id` path parameter to identify the type, then inspect its damage relations, generation, Pokémon, moves, and move damage class.
     */
    fun typeRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): TypeDetail =
        sdk.methods.PokemonTypeRetrieveOperation.typeRetrieve(
            clientConfig,
            id,
            options,
        )
}
