// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk.methods

import sdk.AbilityDetail
import sdk.AbilitySummary
import sdk.CharacteristicDetail
import sdk.CharacteristicSummary
import sdk.ClientConfig
import sdk.EggGroupDetail
import sdk.EggGroupSummary
import sdk.GenderDetail
import sdk.GenderSummary
import sdk.GrowthRateDetail
import sdk.GrowthRateSummary
import sdk.MoveDamageClassDetail
import sdk.MoveDamageClassSummary
import sdk.NatureDetail
import sdk.NatureSummary
import sdk.PaginatedAbilitySummaryList
import sdk.PaginatedCharacteristicSummaryList
import sdk.PaginatedEggGroupSummaryList
import sdk.PaginatedGenderSummaryList
import sdk.PaginatedGrowthRateSummaryList
import sdk.PaginatedMoveDamageClassSummaryList
import sdk.PaginatedNatureSummaryList
import sdk.PaginatedPokemonColorSummaryList
import sdk.PaginatedPokemonFormSummaryList
import sdk.PaginatedPokemonHabitatSummaryList
import sdk.PaginatedPokemonSummaryList
import sdk.PokemonColorDetail
import sdk.PokemonColorSummary
import sdk.PokemonDetail
import sdk.PokemonFormDetail
import sdk.PokemonFormSummary
import sdk.PokemonHabitatDetail
import sdk.PokemonHabitatSummary
import sdk.PokemonSummary
import sdk.RequestOptions
import sdk.SdkClient

internal object PokemonAbilityListOperation {
    /**
     * Lists abilities, which provide passive effects for Pokémon in battle or in the overworld. Use `limit` and `offset` to select a result window, and `q` to filter by name when running a local API instance.
     *
     * Abilities provide passive effects for Pokémon in battle or in the overworld. Pokémon have multiple possible abilities but can have only one ability at a time. Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun abilityList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedAbilitySummaryList {
        return SdkClient.request<PaginatedAbilitySummaryList>(SdkClient.RequestSpec("GET", "/api/v2/ability/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "abilityList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists abilities, which provide passive effects for Pokémon in battle or in the overworld. Use `limit` and `offset` to select a result window, and `q` to filter by name when running a local API instance.
     *
     * Abilities provide passive effects for Pokémon in battle or in the overworld. Pokémon have multiple possible abilities but can have only one ability at a time. Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun abilityListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (AbilitySummary) -> Boolean) {
        var page: PaginatedAbilitySummaryList = abilityList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedAbilitySummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "abilityList", config = clientConfig, options = options)).data
        }
    }



    fun abilityListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (Pokemon.AbilityListPage) -> Boolean) {
        var page: PaginatedAbilitySummaryList = abilityList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(Pokemon.AbilityListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedAbilitySummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "abilityList", config = clientConfig, options = options)).data
        }
    }
}

internal object PokemonAbilityRetrieveOperation {
    /**
     * Retrieves a single ability and its Pokémon, generation, effect, and localized text data. Supply the ability's `id` as a string or integer to look up the record.
     *
     * Abilities provide passive effects for Pokémon in battle or in the overworld. Pokémon have multiple possible abilities but can have only one ability at a time. Check out Bulbapedia for greater detail.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun abilityRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): AbilityDetail {
        return SdkClient.request<AbilityDetail>(SdkClient.RequestSpec("GET", "/api/v2/ability/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "abilityRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }
}

internal object PokemonCharacteristicListOperation {
    /**
     * Lists characteristics that indicate which stat contains a Pokémon's highest individual value (IV). Use `limit` and `offset` to select a result window, and `q` to filter characteristics by name on a local API instance.
     *
     * Characteristics indicate which stat contains a Pokémon's highest IV. A Pokémon's Characteristic is determined by the remainder of its highest IV divided by 5 (gene_modulo). Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun characteristicList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedCharacteristicSummaryList {
        return SdkClient.request<PaginatedCharacteristicSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/characteristic/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "characteristicList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists characteristics that indicate which stat contains a Pokémon's highest individual value (IV). Use `limit` and `offset` to select a result window, and `q` to filter characteristics by name on a local API instance.
     *
     * Characteristics indicate which stat contains a Pokémon's highest IV. A Pokémon's Characteristic is determined by the remainder of its highest IV divided by 5 (gene_modulo). Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun characteristicListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (CharacteristicSummary) -> Boolean) {
        var page: PaginatedCharacteristicSummaryList = characteristicList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedCharacteristicSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "characteristicList", config = clientConfig, options = options)).data
        }
    }



    fun characteristicListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (Pokemon.CharacteristicListPage) -> Boolean) {
        var page: PaginatedCharacteristicSummaryList = characteristicList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(Pokemon.CharacteristicListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedCharacteristicSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "characteristicList", config = clientConfig, options = options)).data
        }
    }
}

internal object PokemonCharacteristicRetrieveOperation {
    /**
     * Retrieves the characteristic that describes which stat contains a Pokémon's highest IV. Use the `id` path parameter to select a characteristic and read its gene modulo, possible values, highest stat, and localized descriptions.
     *
     * Characteristics indicate which stat contains a Pokémon's highest IV. A Pokémon's Characteristic is determined by the remainder of its highest IV divided by 5 (gene_modulo). Check out Bulbapedia for greater detail.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun characteristicRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): CharacteristicDetail {
        return SdkClient.request<CharacteristicDetail>(SdkClient.RequestSpec("GET", "/api/v2/characteristic/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "characteristicRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }
}

internal object PokemonEggGroupListOperation {
    /**
     * Lists egg groups, which determine which Pokémon can interbreed. Use `limit` and `offset` to control the result page, or filter by name with the locally available, case-insensitive `q` query.
     *
     * Egg Groups are categories which determine which Pokémon are able to interbreed. Pokémon may belong to either one or two Egg Groups. Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun eggGroupList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedEggGroupSummaryList {
        return SdkClient.request<PaginatedEggGroupSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/egg-group/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "eggGroupList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists egg groups, which determine which Pokémon can interbreed. Use `limit` and `offset` to control the result page, or filter by name with the locally available, case-insensitive `q` query.
     *
     * Egg Groups are categories which determine which Pokémon are able to interbreed. Pokémon may belong to either one or two Egg Groups. Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun eggGroupListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (EggGroupSummary) -> Boolean) {
        var page: PaginatedEggGroupSummaryList = eggGroupList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedEggGroupSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "eggGroupList", config = clientConfig, options = options)).data
        }
    }



    fun eggGroupListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (Pokemon.EggGroupListPage) -> Boolean) {
        var page: PaginatedEggGroupSummaryList = eggGroupList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(Pokemon.EggGroupListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedEggGroupSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "eggGroupList", config = clientConfig, options = options)).data
        }
    }
}

internal object PokemonEggGroupRetrieveOperation {
    /**
     * Retrieves an egg group that determines which Pokémon can interbreed. Use the `id` path parameter to view the group's name, localized names, and associated Pokémon species.
     *
     * Egg Groups are categories which determine which Pokémon are able to interbreed. Pokémon may belong to either one or two Egg Groups. Check out Bulbapedia for greater detail.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun eggGroupRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): EggGroupDetail {
        return SdkClient.request<EggGroupDetail>(SdkClient.RequestSpec("GET", "/api/v2/egg-group/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "eggGroupRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }
}

internal object PokemonGenderListOperation {
    /**
     * Lists genders used to describe Pokémon, including gender differences relevant to breeding, appearance, and evolution. Use `q` to filter by name, or `limit` and `offset` to control the results page.
     *
     * Genders were introduced in Generation II for the purposes of breeding Pokémon but can also result in visual differences or even different evolutionary lines. Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun genderList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedGenderSummaryList {
        return SdkClient.request<PaginatedGenderSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/gender/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "genderList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists genders used to describe Pokémon, including gender differences relevant to breeding, appearance, and evolution. Use `q` to filter by name, or `limit` and `offset` to control the results page.
     *
     * Genders were introduced in Generation II for the purposes of breeding Pokémon but can also result in visual differences or even different evolutionary lines. Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun genderListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (GenderSummary) -> Boolean) {
        var page: PaginatedGenderSummaryList = genderList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedGenderSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "genderList", config = clientConfig, options = options)).data
        }
    }



    fun genderListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (Pokemon.GenderListPage) -> Boolean) {
        var page: PaginatedGenderSummaryList = genderList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(Pokemon.GenderListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedGenderSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "genderList", config = clientConfig, options = options)).data
        }
    }
}

internal object PokemonGenderRetrieveOperation {
    /**
     * Retrieves a gender and its associated Pokémon species data. Use the `id` path parameter to view the species details and the evolution conditions associated with that gender.
     *
     * Genders were introduced in Generation II for the purposes of breeding Pokémon but can also result in visual differences or even different evolutionary lines. Check out Bulbapedia for greater detail.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun genderRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): GenderDetail {
        return SdkClient.request<GenderDetail>(SdkClient.RequestSpec("GET", "/api/v2/gender/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "genderRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }
}

internal object PokemonGrowthRateListOperation {
    /**
     * Lists growth rates that describe how Pokémon gain levels through experience. Use `q` to filter by name, or `limit` and `offset` to control the results page.
     *
     * Growth rates are the speed with which Pokémon gain levels through experience. Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun growthRateList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedGrowthRateSummaryList {
        return SdkClient.request<PaginatedGrowthRateSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/growth-rate/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "growthRateList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists growth rates that describe how Pokémon gain levels through experience. Use `q` to filter by name, or `limit` and `offset` to control the results page.
     *
     * Growth rates are the speed with which Pokémon gain levels through experience. Check out Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun growthRateListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (GrowthRateSummary) -> Boolean) {
        var page: PaginatedGrowthRateSummaryList = growthRateList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedGrowthRateSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "growthRateList", config = clientConfig, options = options)).data
        }
    }



    fun growthRateListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (Pokemon.GrowthRateListPage) -> Boolean) {
        var page: PaginatedGrowthRateSummaryList = growthRateList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(Pokemon.GrowthRateListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedGrowthRateSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "growthRateList", config = clientConfig, options = options)).data
        }
    }
}

internal object PokemonGrowthRateRetrieveOperation {
    /**
     * Retrieves a growth rate and the experience data associated with it. Use the `id` path parameter to view its formula, localized descriptions, level thresholds, and associated Pokémon species.
     *
     * Growth rates are the speed with which Pokémon gain levels through experience. Check out Bulbapedia for greater detail.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun growthRateRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): GrowthRateDetail {
        return SdkClient.request<GrowthRateDetail>(SdkClient.RequestSpec("GET", "/api/v2/growth-rate/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "growthRateRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }
}

internal object PokemonMoveDamageClassListOperation {
    /**
     * Lists move damage classes, such as physical, special, or non-damaging. Use `q` to filter the results by name with a case-insensitive query; this filter is available locally but not at pokeapi.co.
     *
     * Damage classes moves can have, e.g. physical, special, or non-damaging.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun moveDamageClassList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedMoveDamageClassSummaryList {
        return SdkClient.request<PaginatedMoveDamageClassSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/move-damage-class/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "moveDamageClassList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists move damage classes, such as physical, special, or non-damaging. Use `q` to filter the results by name with a case-insensitive query; this filter is available locally but not at pokeapi.co.
     *
     * Damage classes moves can have, e.g. physical, special, or non-damaging.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun moveDamageClassListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (MoveDamageClassSummary) -> Boolean) {
        var page: PaginatedMoveDamageClassSummaryList = moveDamageClassList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedMoveDamageClassSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "moveDamageClassList", config = clientConfig, options = options)).data
        }
    }



    fun moveDamageClassListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (Pokemon.MoveDamageClassListPage) -> Boolean) {
        var page: PaginatedMoveDamageClassSummaryList = moveDamageClassList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(Pokemon.MoveDamageClassListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedMoveDamageClassSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "moveDamageClassList", config = clientConfig, options = options)).data
        }
    }
}

internal object PokemonMoveDamageClassRetrieveOperation {
    /**
     * Retrieves a move damage class, such as physical, special, or non-damaging. Use the class identifier to look up its descriptions, localized names, and associated moves.
     *
     * Damage classes moves can have, e.g. physical, special, or non-damaging.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun moveDamageClassRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): MoveDamageClassDetail {
        return SdkClient.request<MoveDamageClassDetail>(SdkClient.RequestSpec("GET", "/api/v2/move-damage-class/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "moveDamageClassRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }
}

internal object PokemonNatureListOperation {
    /**
     * Lists natures, which influence how a Pokémon's stats grow. Use `q` to filter the results by name with a case-insensitive query; this filter is available locally but not at pokeapi.co.
     *
     * Natures influence how a Pokémon's stats grow. See Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun natureList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedNatureSummaryList {
        return SdkClient.request<PaginatedNatureSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/nature/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "natureList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists natures, which influence how a Pokémon's stats grow. Use `q` to filter the results by name with a case-insensitive query; this filter is available locally but not at pokeapi.co.
     *
     * Natures influence how a Pokémon's stats grow. See Bulbapedia for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun natureListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (NatureSummary) -> Boolean) {
        var page: PaginatedNatureSummaryList = natureList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedNatureSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "natureList", config = clientConfig, options = options)).data
        }
    }



    fun natureListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (Pokemon.NatureListPage) -> Boolean) {
        var page: PaginatedNatureSummaryList = natureList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(Pokemon.NatureListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedNatureSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "natureList", config = clientConfig, options = options)).data
        }
    }
}

internal object PokemonNatureRetrieveOperation {
    /**
     * Retrieves a nature record describing its effects on Pokémon stats, flavor preferences, and other attributes. Use the nature identifier to look up its stat changes, preferred flavors, and related preferences.
     *
     * Natures influence how a Pokémon's stats grow. See Bulbapedia for greater detail.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun natureRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): NatureDetail {
        return SdkClient.request<NatureDetail>(SdkClient.RequestSpec("GET", "/api/v2/nature/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "natureRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }
}

internal object PokemonListOperation {
    /**
     * Lists Pokémon records representing individual Pokémon and their variants. Use `limit` and `offset` to paginate the results, or use `q` to search Pokémon names when running the API locally.
     *
     * Pokémon are the creatures that inhabit the world of the Pokémon games. They can be caught using Pokéballs and trained by battling with other Pokémon. Each Pokémon belongs to a specific species but may take on a variant which makes it differ from other Pokémon of the same species, such as base stats, available abilities and typings. See Bulbapedia) for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun pokemonList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedPokemonSummaryList {
        return SdkClient.request<PaginatedPokemonSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/pokemon/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "pokemonList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists Pokémon records representing individual Pokémon and their variants. Use `limit` and `offset` to paginate the results, or use `q` to search Pokémon names when running the API locally.
     *
     * Pokémon are the creatures that inhabit the world of the Pokémon games. They can be caught using Pokéballs and trained by battling with other Pokémon. Each Pokémon belongs to a specific species but may take on a variant which makes it differ from other Pokémon of the same species, such as base stats, available abilities and typings. See Bulbapedia) for greater detail.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun pokemonListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (PokemonSummary) -> Boolean) {
        var page: PaginatedPokemonSummaryList = pokemonList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedPokemonSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "pokemonList", config = clientConfig, options = options)).data
        }
    }



    fun pokemonListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (Pokemon.PokemonListPage) -> Boolean) {
        var page: PaginatedPokemonSummaryList = pokemonList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(Pokemon.PokemonListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedPokemonSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "pokemonList", config = clientConfig, options = options)).data
        }
    }
}

internal object PokemonRetrieveOperation {
    /**
     * Retrieves a Pokémon record with its species, abilities, forms, moves, and other game data. Use the Pokémon identifier to distinguish a specific Pokémon variant from its species record.
     *
     * Pokémon are the creatures that inhabit the world of the Pokémon games. They can be caught using Pokéballs and trained by battling with other Pokémon. Each Pokémon belongs to a specific species but may take on a variant which makes it differ from other Pokémon of the same species, such as base stats, available abilities and typings. See Bulbapedia) for greater detail.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun pokemonRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): PokemonDetail {
        return SdkClient.request<PokemonDetail>(SdkClient.RequestSpec("GET", "/api/v2/pokemon/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "pokemonRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }
}

internal object PokemonColorListOperation {
    /**
     * Lists colors used to sort Pokémon in a Pokédex. Use `limit` and `offset` to paginate the results, or use `q` to search color names when running the API locally.
     *
     * Colors used for sorting Pokémon in a Pokédex. The color listed in the Pokédex is usually the color most apparent or covering each Pokémon's body. No orange category exists; Pokémon that are primarily orange are listed as red or brown.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun pokemonColorList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedPokemonColorSummaryList {
        return SdkClient.request<PaginatedPokemonColorSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/pokemon-color/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "pokemonColorList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists colors used to sort Pokémon in a Pokédex. Use `limit` and `offset` to paginate the results, or use `q` to search color names when running the API locally.
     *
     * Colors used for sorting Pokémon in a Pokédex. The color listed in the Pokédex is usually the color most apparent or covering each Pokémon's body. No orange category exists; Pokémon that are primarily orange are listed as red or brown.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun pokemonColorListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (PokemonColorSummary) -> Boolean) {
        var page: PaginatedPokemonColorSummaryList = pokemonColorList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedPokemonColorSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "pokemonColorList", config = clientConfig, options = options)).data
        }
    }



    fun pokemonColorListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (Pokemon.PokemonColorListPage) -> Boolean) {
        var page: PaginatedPokemonColorSummaryList = pokemonColorList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(Pokemon.PokemonColorListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedPokemonColorSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "pokemonColorList", config = clientConfig, options = options)).data
        }
    }
}

internal object PokemonColorRetrieveOperation {
    /**
     * Retrieves a Pokémon color record and the species associated with that color. Use the color identifier to look up its localized names and related Pokémon species.
     *
     * Colors used for sorting Pokémon in a Pokédex. The color listed in the Pokédex is usually the color most apparent or covering each Pokémon's body. No orange category exists; Pokémon that are primarily orange are listed as red or brown.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun pokemonColorRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): PokemonColorDetail {
        return SdkClient.request<PokemonColorDetail>(SdkClient.RequestSpec("GET", "/api/v2/pokemon-color/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "pokemonColorRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }
}

internal object PokemonFormListOperation {
    /**
     * Lists cosmetic forms in which Pokémon can appear. Use `limit` and `offset` to paginate the results, or use `q` to search form names when running the API locally.
     *
     * Some Pokémon may appear in one of multiple, visually different forms. These differences are purely cosmetic. For variations within a Pokémon species, which do differ in more than just visuals, the 'Pokémon' entity is used to represent such a variety.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun pokemonFormList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedPokemonFormSummaryList {
        return SdkClient.request<PaginatedPokemonFormSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/pokemon-form/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "pokemonFormList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists cosmetic forms in which Pokémon can appear. Use `limit` and `offset` to paginate the results, or use `q` to search form names when running the API locally.
     *
     * Some Pokémon may appear in one of multiple, visually different forms. These differences are purely cosmetic. For variations within a Pokémon species, which do differ in more than just visuals, the 'Pokémon' entity is used to represent such a variety.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun pokemonFormListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (PokemonFormSummary) -> Boolean) {
        var page: PaginatedPokemonFormSummaryList = pokemonFormList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedPokemonFormSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "pokemonFormList", config = clientConfig, options = options)).data
        }
    }



    fun pokemonFormListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (Pokemon.PokemonFormListPage) -> Boolean) {
        var page: PaginatedPokemonFormSummaryList = pokemonFormList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(Pokemon.PokemonFormListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedPokemonFormSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "pokemonFormList", config = clientConfig, options = options)).data
        }
    }
}

internal object PokemonFormRetrieveOperation {
    /**
     * Retrieves a Pokémon form, which represents a cosmetic variation of a Pokémon. Use `id` to select the form and inspect its Pokémon, version group, types, localized names, and trigger conditions.
     *
     * Some Pokémon may appear in one of multiple, visually different forms. These differences are purely cosmetic. For variations within a Pokémon species, which do differ in more than just visuals, the 'Pokémon' entity is used to represent such a variety.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun pokemonFormRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): PokemonFormDetail {
        return SdkClient.request<PokemonFormDetail>(SdkClient.RequestSpec("GET", "/api/v2/pokemon-form/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "pokemonFormRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }
}

internal object PokemonHabitatListOperation {
    /**
     * Lists Pokémon habitats, which describe terrain where Pokémon can be found or areas designated for rare or legendary Pokémon. Use `limit` and `offset` to page through results, or use `q` to filter by name; `q` is available only on local installations.
     *
     * Habitats are generally different terrain Pokémon can be found in but can also be areas designated for rare or legendary Pokémon.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun pokemonHabitatList(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null): PaginatedPokemonHabitatSummaryList {
        return SdkClient.request<PaginatedPokemonHabitatSummaryList>(SdkClient.RequestSpec("GET", "/api/v2/pokemon-habitat/", config = clientConfig, query = mapOf("limit" to SdkClient.queryValue(limit, "form", true), "offset" to SdkClient.queryValue(offset, "form", true), "q" to SdkClient.queryValue(q, "form", true)), operationId = "pokemonHabitatList", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }






    /**
     * Lists Pokémon habitats, which describe terrain where Pokémon can be found or areas designated for rare or legendary Pokémon. Use `limit` and `offset` to page through results, or use `q` to filter by name; `q` is available only on local installations.
     *
     * Habitats are generally different terrain Pokémon can be found in but can also be areas designated for rare or legendary Pokémon.
     *
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q > Only available locally and not at pokeapi.co Case-insensitive query
     *   applied on the `name` property.
     */
    fun pokemonHabitatListPaginated(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldFn: (PokemonHabitatSummary) -> Boolean) {
        var page: PaginatedPokemonHabitatSummaryList = pokemonHabitatList(clientConfig, limit, offset, q, options)
        while (true) {
            for (item in page.results.orEmpty()) {
                if (!yieldFn(item)) return
            }
            val nextUrl = page.next ?: return
            page = SdkClient.request<PaginatedPokemonHabitatSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "pokemonHabitatList", config = clientConfig, options = options)).data
        }
    }



    fun pokemonHabitatListPages(clientConfig: ClientConfig, limit: Int? = null, offset: Int? = null, q: String? = null, options: RequestOptions? = null, yieldPage: (Pokemon.PokemonHabitatListPage) -> Boolean) {
        var page: PaginatedPokemonHabitatSummaryList = pokemonHabitatList(clientConfig, limit, offset, q, options)
        while (true) {
            val items = page.results.orEmpty()
            val nextUrl = page.next
            val hasMore = !nextUrl.isNullOrEmpty()
            if (!yieldPage(Pokemon.PokemonHabitatListPage(page, items, hasMore))) return
            if (!hasMore) return
            page = SdkClient.request<PaginatedPokemonHabitatSummaryList>(SdkClient.RequestSpec(method = "GET", path = nextUrl, operationId = "pokemonHabitatList", config = clientConfig, options = options)).data
        }
    }
}

internal object PokemonHabitatRetrieveOperation {
    /**
     * Retrieves a Pokémon habitat, which describes terrain where Pokémon can be found or an area designated for rare or legendary Pokémon. Use `id` to select a habitat and view its localized names and associated Pokémon species.
     *
     * Habitats are generally different terrain Pokémon can be found in but can also be areas designated for rare or legendary Pokémon.
     *
     * @param id This parameter can be a string or an integer.
     */
    fun pokemonHabitatRetrieve(clientConfig: ClientConfig, id: String, options: RequestOptions? = null): PokemonHabitatDetail {
        return SdkClient.request<PokemonHabitatDetail>(SdkClient.RequestSpec("GET", "/api/v2/pokemon-habitat/${SdkClient.encodePathSegment(id)}/", config = clientConfig, operationId = "pokemonHabitatRetrieve", decoder = SdkClient.ResponseDecoder.JSON, options = options)).data
    }
}
