// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import java.io.File
import java.net.URLDecoder
import java.time.Duration
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Data-driven behavior suite: replays every shared behavior case through the request layer with a
 * fake middleware transport. Schema-independent — the fixture in test/sdk-behavior-cases.json
 * carries the per-operation detail.
 */
class SdkBehaviorTest {
    private val mapper = ObjectMapper()

    /**
     * Space is "+" in form encoding and "%20" under RFC 3986; pair order is not part of the
     * contract either.
     */
    private fun normalizeQuery(query: String?): String {
        if (query.isNullOrEmpty()) return ""
        return query
            .split("&")
            .map { pair ->
                val parts = pair.split("=", limit = 2)
                val name = URLDecoder.decode(parts[0], "UTF-8")
                val value = if (parts.size > 1) URLDecoder.decode(parts[1], "UTF-8") else ""
                "$name=$value"
            }
            .sorted()
            .joinToString("&")
    }

    private fun decoderFor(kind: String): SdkClient.ResponseDecoder =
        when (kind) {
            "text" -> SdkClient.ResponseDecoder.TEXT
            "bytes" -> SdkClient.ResponseDecoder.BYTES
            "empty" -> SdkClient.ResponseDecoder.EMPTY
            else -> SdkClient.ResponseDecoder.JSON
        }

    private fun jsonValue(node: JsonNode?): Any? =
        if (node == null || node.isNull) null else mapper.treeToValue(node, Any::class.java)

    @Test
    fun replaysEveryGeneratedBehaviorCase() {
        val fixture = mapper.readTree(File("test/sdk-behavior-cases.json"))
        val baseUrl = fixture.get("baseUrl").asText()
        val authHeaders = mutableMapOf<String, String>()
        fixture.get("authHeaders").fields().forEach { (name, value) ->
            authHeaders[name] = value.asText()
        }
        val cases = fixture.get("cases")
        val operationCount = fixture.get("operationCount").asInt()
        assertEquals(
            operationCount == 0,
            cases.size() == 0,
            "behavior fixture presence does not match ordinary operations",
        )

        for (case in cases) {
            replayCase(case, baseUrl, authHeaders)
        }
    }

    /** Replays one case. Split out so detekt's LongMethod rule stays satisfied. */
    @Suppress("LongMethod", "CyclomaticComplexMethod")
    private fun replayCase(
        case: JsonNode,
        baseUrl: String,
        authHeaders: Map<String, String>,
    ) {
        run {
            val id = case.get("id").asText()
            val requestSpec = case.get("request").takeIf { !it.isNull }
            val responseSpec = case.get("response")
            val status = responseSpec.get("status").asInt()
            val mediaType = responseSpec.get("mediaType").takeIf { !it.isNull }?.asText()
            var seen: SdkRequest? = null

            val config =
                ClientConfig(
                    baseUrl = baseUrl,
                    auth = ClientAuthConfig(headers = authHeaders.toMap()),
                    retry = RetryConfig(maxAttempts = 1),
                    idempotency = IdempotencyConfig(enabled = false),
                    middleware =
                        listOf({ request, _ ->
                            seen = request
                            SdkRawResponse(
                                statusCode = status,
                                statusText = "",
                                headers =
                                    if (mediaType == null) emptyMap()
                                    else mapOf("content-type" to mediaType),
                                body =
                                    if (status == 204) {
                                        ByteArray(0)
                                    } else {
                                        responseSpec.get("body").asText().toByteArray()
                                    },
                                requestId = null,
                                latency = Duration.ofMillis(1),
                                attempt = request.attempt,
                            )
                        }),
                )

            var method = "GET"
            var path = "/behavior/$id"
            val query = mutableMapOf<String, Any?>()
            var body: Any? = null
            var contentType = "application/json"
            var extraHeaders = emptyMap<String, String>()
            var bodyKind: String? = null
            if (requestSpec != null) {
                method = requestSpec.get("method").asText()
                path = requestSpec.get("pathTemplate").asText()
                requestSpec.get("pathParameters").fields().forEach { (name, value) ->
                    path = path.replace("{$name}", SdkClient.encodePathSegment(jsonValue(value)))
                }
                for (parameter in requestSpec.get("query")) {
                    val value = jsonValue(parameter.get("value")) ?: continue
                    query[parameter.get("name").asText()] =
                        SdkClient.queryValue(
                            value,
                            parameter.get("style").asText(),
                            parameter.get("explode").asBoolean(),
                        )
                }
                val headerInputs = mutableMapOf<String, String>()
                requestSpec.get("headers").fields().forEach { (name, value) ->
                    headerInputs[name] = value.asText()
                }
                extraHeaders = headerInputs
                bodyKind = requestSpec.get("bodyKind").takeIf { !it.isNull }?.asText()
                if (bodyKind != null) {
                    body = jsonValue(requestSpec.get("body"))
                    contentType = requestSpec.get("contentType").asText()
                }
            }

            val spec =
                SdkClient.RequestSpec(
                    method = method,
                    path = path,
                    config = config,
                    query = query,
                    body = body,
                    contentType = contentType,
                    operationId = case.get("operationId").asText(),
                    extraHeaders = extraHeaders,
                    decoder = decoderFor(responseSpec.get("kind").asText()),
                )

            if (status >= 400) {
                // A 4xx/5xx case must throw the typed error carrying the payload.
                var thrown: SdkHttpError? = null
                try {
                    SdkClient.request<Any?>(spec)
                } catch (error: SdkHttpError) {
                    thrown = error
                }
                assertNotNull(thrown, "$id expected SdkHttpError for status $status")
                assertEquals(status, thrown.statusCode, "$id typed error status")
                val errorKind = responseSpec.path("errorKind").asText("")
                assertEquals(
                    if (errorKind.isEmpty()) "SdkHttpError" else "Sdk${errorKind}Error",
                    thrown.javaClass.simpleName,
                    "$id typed error class",
                )
                if (responseSpec.has("value")) {
                    assertEquals(
                        jsonValue(responseSpec.get("value")),
                        jsonValue(mapper.readTree(thrown.bodyText)),
                        "$id typed error body",
                    )
                }
            } else {
                val response = SdkClient.request<Any?>(spec)
                assertEquals(status, response.statusCode, "$id status")
                if (responseSpec.has("value")) {
                    val kind = responseSpec.get("kind").asText()
                    val expected = jsonValue(responseSpec.get("value"))
                    val actual: Any? =
                        when (kind) {
                            "bytes" -> (response.data as? ByteArray)?.size
                            else -> response.data
                        }
                    if (kind == "json" || kind == "text" || kind == "bytes") {
                        assertEquals(expected, actual, "$id decoded response")
                    }
                }
            }

            if (requestSpec == null) return@run
            val sentRequest = seen
            assertNotNull(sentRequest, "$id middleware never saw a request")
            val expectation = case.get("expect")
            assertEquals(expectation.get("method").asText(), sentRequest.method, "$id method")
            val gotParts = sentRequest.url.split("?", limit = 2)
            val wantParts = expectation.get("url").asText().split("?", limit = 2)
            assertEquals(wantParts[0], gotParts[0], "$id url path")
            assertEquals(
                normalizeQuery(wantParts.getOrNull(1)),
                normalizeQuery(gotParts.getOrNull(1)),
                "$id url query",
            )
            val sentHeaders =
                sentRequest.headers.entries.associate { it.key.lowercase() to it.value }
            val multipart = !expectation.get("multipartFields").isNull
            expectation.get("headers").fields().forEach { (name, value) ->
                val actual = sentHeaders[name.lowercase()] ?: ""
                if (name == "content-type" && multipart) {
                    assertTrue(
                        actual.startsWith("multipart/form-data"),
                        "$id multipart content type",
                    )
                } else {
                    assertEquals(value.asText(), actual, "$id header $name")
                }
            }
            val expectedBody = expectation.get("bodyText").takeIf { !it.isNull }?.asText()
            if (expectedBody != null && bodyKind == "json") {
                assertEquals(
                    jsonValue(mapper.readTree(expectedBody)),
                    jsonValue(mapper.readTree(sentRequest.body ?: "null")),
                    "$id request body",
                )
            }
        }
    }
}
