// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

package sdk


import com.fasterxml.jackson.databind.JavaType
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.SerializationFeature
import java.io.File
import java.lang.reflect.Method
import java.lang.reflect.Modifier
import java.lang.reflect.ParameterizedType
import java.lang.reflect.Type
import java.time.Instant
import java.time.OffsetDateTime
import java.util.concurrent.CompletableFuture
import kotlin.coroutines.Continuation
import kotlin.coroutines.EmptyCoroutineContext
import kotlin.coroutines.intrinsics.suspendCoroutineUninterceptedOrReturn
import kotlin.coroutines.startCoroutine
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

class SdkMethodTest {
    // Configured the way the SDK configures its own mapper, so a value read back out
    // of a decoded response is spelled the way the SDK spells it on the wire.
    // Jackson's default writes a timestamp as a number of seconds since the epoch.
    private val mapper =
        ObjectMapper()
            .findAndRegisterModules()
            .disable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE)
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)

    private fun normalized(value: String): String = value.filter(Char::isLetterOrDigit).lowercase()

    // An exact key wins: distinct wire keys (foo-bar, foo_bar) share a normalized name.
    private fun byName(
        value: JsonNode?,
        name: String,
    ): JsonNode? =
        value?.get(name) ?: value
            ?.fields()
            ?.asSequence()
            ?.firstOrNull { normalized(it.key) == normalized(name) }
            ?.value

    // A parameter object standing in for the whole argument list, whose fields the
    // fixture states at the top level under no name of its own. It is declared
    // inside the class holding the method, which is what separates it from a body
    // typed as a model whose name happens to end the same way.
    private fun aggregate(raw: Class<*>): Boolean =
        raw.enclosingClass != null &&
            (
                raw.simpleName.endsWith("Request") ||
                    raw.simpleName.endsWith("Params") ||
                    raw.simpleName.endsWith("Options")
            )

    private fun absentValue(raw: Class<*>): Any? =
        when (raw) {
            java.lang.Boolean.TYPE -> false
            java.lang.Integer.TYPE,
            java.lang.Long.TYPE,
            java.lang.Double.TYPE,
            java.lang.Float.TYPE,
            -> 0
            else -> null
        }

    private fun listValue(
        type: ParameterizedType,
        value: JsonNode,
    ): List<Any?> {
        // Converted one element at a time, so an element type this method
        // knows how to build - a file part, say - is built the same way in
        // a list as it is on its own.
        val element = type.actualTypeArguments[0]
        return value.map { convert(element, it) }
    }

    private fun uploadFile(
        raw: Class<*>,
        value: JsonNode,
    ): Any {
        // A multipart file part. The fixture states the file as its text,
        // which is the payload the mock compares against.
        val text = if (value.isTextual) value.asText() else value.toString()
        return raw.getConstructor(ByteArray::class.java, String::class.java, String::class.java)
            .newInstance(text.toByteArray(Charsets.UTF_8), "upload", "application/octet-stream")
    }

    private fun optionalValue(
        type: Type,
        raw: Class<*>,
        value: JsonNode,
    ): Any {
        // A tri-state optional parameter. The fixture states a value, so the
        // call has to receive it as present; the sealed interface itself has
        // no constructor for Jackson to reach for.
        val inner = (type as? ParameterizedType)?.actualTypeArguments?.firstOrNull()
        val present = raw.declaredClasses.first { it.simpleName == "Present" }
        val constructor = present.declaredConstructors.first()
        constructor.isAccessible = true
        return constructor.newInstance(inner?.let { convert(it, value) })
    }

    private fun objectValue(
        javaType: JavaType,
        raw: Class<*>,
        value: JsonNode,
    ): Any? {
        // Kotlin emits a synthetic overload carrying a default-argument mask
        // alongside the primary constructor; only the primary one lines up with
        // the declared fields.
        val constructor =
            raw.declaredConstructors
                .filter { !it.isSynthetic }
                .maxByOrNull { it.parameterCount }
                ?: return mapper.convertValue(value, javaType)
        val fields =
            raw.declaredFields.filter {
                !Modifier.isStatic(it.modifiers) && !it.isSynthetic
            }
        // Constructor parameters are matched to properties by position, which only
        // holds while the two line up. A class that carries more parameters than
        // declared fields - a default-argument mask, say - is left to Jackson.
        if (fields.size < constructor.parameterCount) return mapper.convertValue(value, javaType)
        constructor.isAccessible = true
        val values =
            constructor.genericParameterTypes
                .mapIndexed { index, parameterType ->
                    convert(parameterType, byName(value, fields[index].name))
                }.toTypedArray()
        return constructor.newInstance(*values)
    }

    private fun convert(
        type: Type,
        value: JsonNode?,
    ): Any? {
        val javaType: JavaType = mapper.typeFactory.constructType(type)
        val raw = javaType.rawClass
        return when {
            value == null || value.isNull -> absentValue(raw)
            type is ParameterizedType && raw == List::class.java -> listValue(type, value)
            raw.isPrimitive || raw.isEnum || raw.name.startsWith("java.") || raw == Any::class.java ->
                mapper.convertValue(value, javaType)
            type is ParameterizedType && raw == Map::class.java -> mapper.convertValue(value, javaType)
            raw.simpleName == "UploadFile" -> uploadFile(raw, value)
            !value.isObject && raw.simpleName != "SdkOptional" ->
                // Only an object node has properties to match against constructor
                // parameters. A scalar reaching a generated class means the class wraps
                // that scalar - an open enum, say - and it declares the creator Jackson
                // needs to build it.
                mapper.convertValue(value, javaType)
            raw.simpleName == "SdkOptional" -> optionalValue(type, raw, value)
            else -> objectValue(javaType, raw, value)
        }
    }

    /** The path at which the decoded response departs from the mock, or null when it does not. */
    private fun objectMismatch(
        actual: JsonNode?,
        expected: JsonNode,
        path: String,
    ): String? =
        if (actual == null || !actual.isObject) {
            "$path: expected an object, decoded $actual"
        } else {
            expected
                .fields()
                .asSequence()
                .firstNotNullOfOrNull { (name, value) ->
                    val child = byName(actual, name)
                    if (child == null) {
                        "$path.$name: missing from the decoded response"
                    } else {
                        mismatch(child, value, "$path.$name")
                    }
                }
        }

    private fun arrayMismatch(
        actual: JsonNode?,
        expected: JsonNode,
        path: String,
    ): String? =
        when {
            actual == null || !actual.isArray -> "$path: expected an array, decoded $actual"
            actual.size() != expected.size() ->
                "$path: decoded ${actual.size()} items, the mock states ${expected.size()}"
            else ->
                expected.withIndex().firstNotNullOfOrNull { (index, value) ->
                    mismatch(actual[index], value, "$path[$index]")
                }
        }

    private fun instant(value: String): Instant? = runCatching { OffsetDateTime.parse(value).toInstant() }.getOrNull()

    private fun mismatch(
        actual: JsonNode?,
        expected: JsonNode?,
        path: String = "response",
    ): String? =
        when {
            expected == null || expected.isNull ->
                if (actual == null || actual.isNull) null else "$path: expected null, decoded $actual"
            expected.isObject -> objectMismatch(actual, expected, path)
            expected.isArray -> arrayMismatch(actual, expected, path)
            // A number is compared by value: a field typed as a floating point
            // decodes 0 as 0.0, which is the same number the mock stated.
            expected.isNumber -> {
                val same =
                    actual != null &&
                        actual.isNumber &&
                        expected.decimalValue().compareTo(actual.decimalValue()) == 0
                if (same) null else "$path: decoded $actual, the mock states $expected"
            }
            // A timestamp is compared as an instant: the mock states whatever
            // precision the API documents, and the SDK writes its own.
            expected.isTextual && actual != null && actual.isTextual &&
                instant(expected.asText()).let { it != null && it == instant(actual.asText()) } -> null
            // Decoded bytes stay a binary node; their text is the base64 the mock sent.
            expected.isTextual && actual != null && actual.isBinary ->
                if (expected.asText() == actual.asText()) null else "$path: decoded $actual, the mock states $expected"
            else -> if (actual == expected) null else "$path: decoded $actual, the mock states $expected"
        }

    // Under the suspending surface (ktor) a method's last parameter is its
    // continuation, and a stream is a coroutine Flow. Both are driven with the
    // standard library, and the Flow is read through the coroutine library by
    // name, so the suite still compiles for the blocking surface, which has none.
    private val firstOfFlow: Method? =
        runCatching {
            Class
                .forName("kotlinx.coroutines.flow.FlowKt")
                .getMethod("firstOrNull", Class.forName("kotlinx.coroutines.flow.Flow"), Continuation::class.java)
        }.getOrNull()

    private fun invokeSuspending(
        method: Method,
        instance: Any?,
        values: List<Any?>,
    ): Any? {
        val result = CompletableFuture<Any?>()
        val call: suspend () -> Any? = {
            suspendCoroutineUninterceptedOrReturn { continuation ->
                method.invoke(instance, *values.toTypedArray(), continuation)
            }
        }
        call.startCoroutine(Continuation(EmptyCoroutineContext) { it.fold(result::complete, result::completeExceptionally) })
        return result.get()
    }

    @Test
    fun everyGeneratedMethodReachesMockAndDecodesItsResponse() {
        val baseUrl = System.getenv("SDK_METHOD_TEST_BASE_URL") ?: return
        SdkConfig.configure(ClientConfig(baseUrl = baseUrl))
        val cases = mapper.readTree(File("test/sdk-method-cases.json")).get("cases")
        assertTrue(cases.size() > 0, "method fixture is empty")
        for (caseData in cases) {
            val owner = Class.forName(caseData.get("owner").asText())
            val methodName = caseData.get("methodName").asText()
            val method = owner.methods.first { it.name == methodName && !it.isSynthetic }
            val instance = owner.fields.firstOrNull { it.name == "INSTANCE" }?.get(null)
            val arguments = caseData.get("arguments")
            val order = caseData.get("argumentOrder")
            var positional = 0
            val suspending = method.parameterTypes.lastOrNull() == Continuation::class.java
            val values =
                method.genericParameterTypes
                    .take(method.parameterCount - if (suspending) 1 else 0)
                    .mapIndexed { index, type ->
                        val raw = method.parameterTypes[index]
                        when {
                            raw == ClientConfig::class.java -> SdkConfig.getConfig()
                            // Per-call options are the SDK's own, never an operation argument.
                            raw.simpleName == "RequestOptions" -> null
                            aggregate(raw) -> convert(type, arguments)
                            else -> {
                                val input =
                                    byName(arguments, method.parameters[index].name)
                                        ?: order.get(positional++)?.let { byName(arguments, it.asText()) }
                                convert(type, input)
                            }
                        }
                    }
            var actual =
                if (suspending) invokeSuspending(method, instance, values) else method.invoke(instance, *values.toTypedArray())
            // A method with no response body returns Unit, which reflection hands
            // back as a value rather than as the absence of one.
            if (actual == Unit) actual = null
            if (caseData.get("mode").asText() == "stream") {
                actual =
                    when (val stream = actual) {
                        is Sequence<*> -> stream.firstOrNull()
                        is Iterable<*> -> stream.firstOrNull()
                        is Iterator<*> -> if (stream.hasNext()) stream.next() else null
                        else ->
                            if (firstOfFlow?.parameterTypes?.first()?.isInstance(stream) == true) {
                                invokeSuspending(firstOfFlow, null, listOf(stream))
                            } else {
                                stream
                            }
                    }
            }
            val response = caseData.get("response")
            when (response.get("kind").asText()) {
                "empty" -> assertEquals(null, actual, caseData.get("id").asText())
                "bytes" ->
                    assertEquals(
                        response.get("byteLength").asInt(),
                        (actual as ByteArray).size,
                        caseData.get("id").asText(),
                    )
                else ->
                    assertNull(
                        mismatch(mapper.valueToTree(actual), response.get("expected")),
                        caseData.get("id").asText() + " decoded a response that differs from the mock",
                    )
            }
        }
    }
}
